### ISSUE TITLE
print template

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#1]
Print skabelon med byvåben i VIDI´s standard template.
Med teksten Nyborg Kommune   - Danmarks Riges Hjerte

**Comment by Nyborg1** [comment]
Print-template har en "datetime" i css
Er det muligt at fjerne tiden?
Findes der en standard-variable til det?
![image](https://user-images.githubusercontent.com/95336810/200824791-f63aef18-d71e-45da-835a-3346a1505454.png)

**Comment by Nyborg1** [comment]
Kortvinduet viser ikke printrammen korrekt. 
Korthoved med logo lapper ind over kortet i printet.
![2023-02-02 13_07_17-MapCentia Vidi – Google Chrome](https://user-images.githubusercontent.com/95336810/216320737-2556a8cb-a19f-4982-8535-da3f81237696.png)
![2023-02-02 13_08_07-603a3d76-f490-48fa-8c1b-85778e2da5e3 pdf – Google Chrome](https://user-images.githubusercontent.com/95336810/216320758-18ad15ce-62c7-4c48-b306-28211520cf4f.png)

**Comment by mapcentia** [comment]
Det skulle passe nu. Før var kort-hovedet placeret ovenpå kortet, men nu er det placeret under. Så det man ser i Vidi skulle gerne passe til det man ser på print

**Comment by Nyborg1** [comment]
Jeg er ikke sikker på at det er godt.
Nu er pdf-filen delt i 2 sider - og der er kommet et gammelt byvåben på igen.

![2023-02-10 11_04_13-ca70a6b3-14d5-4dec-84da-3a0db50e4a7b pdf – Google Chrome](https://user-images.githubusercontent.com/95336810/218063441-6f9b0886-0706-4e90-9470-8e145c166ac4.png)

**Comment by mapcentia** [comment]
Jeg skulle lige have den interne opdateret også - nu skulle det se rigtigt ud

**Comment by Nyborg1** [comment]
:-)  Nu ser det rigtigt ud..
Umiddelbart ser det pænt ud nu.
Men jeg synes ikke helt at målforholdet passer på print..  Jeg opretter et andet issue om det
