### ISSUE TITLE
Default template for Nyborg - hvor?

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#10]
Hvor ligger default.tmpl for konfigurationerne i Nyborg.

Kan der ligges en kopi i Github?

Det er svær t at gennemskue hvordan Nyborg-specifikke sætte op uden jeg ved hvordan default ser ud :-)

**Comment by mapcentia** [comment]
Alle mulige indstillinger i en config kan ses her:
https://vidi.readthedocs.io/da/latest/pages/standard/91_run_configuration.html

**Comment by mapcentia** [comment]
Lukker
