### ISSUE TITLE
Indlejrede kort på Umbraco-cms

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#11]
Vi har nu adgang til et at teste på Nyborgs intranet.
Det er lykkede mig at lægge et link og en png på. Men jeg ka ikke få token til at virke
Hvor skal scriptet placeres?
<script src="https://vidi.swarm.gc2.io/js/embed.js"></script>
Ved du hvor man får adgang til side-skabelonen i Umbraco?

**Comment by Nyborg1** [comment]
Placeres eet sted - fx det eksterne site.
<script src="https://kort.nyborg.dk/js/embed.js"></script>

**Comment by mapcentia** [comment]
Jeg lukker denne her
