### ISSUE TITLE
Fejl i databasen - igen

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#12]
Konfigurationerne  "intern" og "byggesag"  har gammelt indhold? 
Rettelser fra i fredags er væk - overskrevet med gammelt indhold!

Er der noget synkronisering som er skyld i dette?

Bl.a. er nye baggrundskort med ortofoto Forår 2022 og sommer 2022 forsvundet ud af konfigurationerne

**Comment by Nyborg1** [comment]
Det er de nye konfigurationer der ligger på den eksterne database https://nyborg.admin.gc2.io/dashboard/

**Comment by mapcentia** [comment]
Jeg tror, at jeg har fundet ud af det. Der er to PostgreSQL installationer: v13 og v14. Det er meningen, at det er v14, som kører, men Windows Serveren bliver genstartet (måske hver weekend?) og begge Postgres-databaser er sat til automatisk opstart. Da begge benytter port 5432 kan kun én køre og er det tilfældigt hvilken version, der kommer først. Da jeg tjekkede kørte v13 og da jeg skiftede til v14 er Forår 2022 og sommer 2022 med igen. Nu er v13 sat til manuel opstart. Så nu skal det tjekkes om alt er i v14 og bagefter skal v13 afinstalleres.

**Comment by Nyborg1** [comment]
De findes ikke længere i den lokale nyborg_gis

**Comment by Nyborg1** [comment]
Den gamle database v 13 kan afinstalleres når der er gemt en backup af indholdet.
