### ISSUE TITLE
Manglende synkronisering til ekstern

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#13]
Der sker ingen synkronisering fra 
https://gc2.nyborg.dk/
til 
https://nyborg.admin.gc2.io/

Hvor kan jeg se hvad der bliver synkronisteret?
Hvad skal der gøres for at det eksterne sit bliver synligt - internt  ?
- se tidligere issues!

**Comment by mapcentia** [comment]
Er sat op i crontab nu. Sync er lige kørt
