### ISSUE TITLE
Baselayers: baggrundskort med kombinerede wms-kilder

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#14]
Hvordan kombineres forskellige wms-kilder, så de kan bruges som et baggrundskort i baselayers:

Ortofoto fra DAF:
        {
            "type": "wms",
            "url": "https://api.dataforsyningen.dk/orto_foraar_DAF?token=0e2dd7a0ee145e0993dfcb4376e18f1a",
            "layers": [
                "geodanmark_2021_12_5cm"
            ],
            "id": "geodanmark_2021_12_5cm",
            "name": "Luftfoto 2021",
            "description": "Ortofotos anvendes til ajourføring af de topografiske grunddata. Optagelsestidspunkt for ortofotos er om foråret før løvspring.",
            "attribution": "GeoDanmark",
            "minZoom": 8,
            "maxZoom": 26,
            "maxNativeZoom": 22,
            "transparent": true
        },

**Og husnumre og vejnavne fra dataforsyningen:**

        {
            "type": "wms",
            "url": "https://api.dataforsyningen.dk/forvaltning2?token=eaca82e1cb411d78e841c7eba8ec1bbc",
            "layers": [
                "Vejnavne_ortofoto",
                "Husnummer_ortofoto"
            ],
            "id": "Vejnavne_husnr_ortofoto",
            "name": "Vejnavne, husnr og ortofoto 2021",
            "description": "Ortofotos anvendes til ajourføring af de topografiske grunddata. Optagelsestidspunkt for ortofotos er om foråret før løvspring.",
            "attribution": "Styrelsen for Dataforsyning og Effektivisering",
            "minZoom": 8,
            "maxZoom": 26,
            "maxNativeZoom": 22,
            "transparent": true
        },

**Og så matrikler**
        {
            "type": "wms",
            "url": "https://api.dataforsyningen.dk/forvaltning2?token=eaca82e1cb411d78e841c7eba8ec1bbc",
            "layers": [
                "Matrikel",
                "Matrikel-foreloebig",
                "Matrikel-tekst"
            ],
            "id": "Basis_kort",
            "name": "Forvaltningskort matr",
            "description": "Forvaltningskort",
            "attribution": "Nyborg Kommune",
            "minZoom": 8,
            "maxZoom": 22,
            "maxNativeZoom": 22,
            "transparent": true
        },

**Comment by mapcentia** [comment]
Jeg opdagede en fejl i overlay funktionen ved brug af eksterne WMS'er. Den er rettet med jeg skal lige have rullet den ud. Ellers skal opsætningen se sådan ud:

```json
 {
            "type": "wms",
            "url": "https://api.dataforsyningen.dk/orto_foraar_DAF?token=0e2dd7a0ee145e0993dfcb4376e18f1a",
            "layers": [
                "geodanmark_2021_12_5cm"
            ],
            "id": "geodanmark_2021_12_5cm",
            "name": "Luftfoto 2021",
            "description": "Ortofotos anvendes til ajourføring af de topografiske grunddata. Optagelsestidspunkt for ortofotos er om foråret før løvspring.",
            "attribution": "GeoDanmark",
            "minZoom": 8,
            "maxZoom": 26,
            "maxNativeZoom": 22,
            "transparent": true,
            "overlays": [
                {
                    "type": "wms",
                    "url": "https://api.dataforsyningen.dk/forvaltning2?token=eaca82e1cb411d78e841c7eba8ec1bbc",
                    "layers": [
                        "Vejnavne_ortofoto",
                        "Husnummer_ortofoto"
                    ],
                    "id": "Vejnavne_husnr_ortofoto",
                    "transparent": true,
                    "format": "image/png",
                    "maxZoom": 26
                },
                {
                    "type": "wms",
                    "url": "https://api.dataforsyningen.dk/forvaltning2?token=eaca82e1cb411d78e841c7eba8ec1bbc",
                    "layers": [
                        "Matrikel",
                        "Matrikel-foreloebig",
                        "Matrikel-tekst"
                    ],
                    "id": "Basis_kort",
                    "transparent": true,
                    "format": "image/png",
                    "maxZoom": 26
                }
            ]
        }
```

**Comment by mapcentia** [comment]
Prøv nu "Byggesag test"

**Comment by Nyborg1** [comment]
Det virker fint
Er det muligt at tilføje et databaselag til det nye baggrundskort.
Det er ikke muligt at få **ejerlavs navn** vist på via de tilgængelige tjenester fra sdfi
tabellen hedder _01_04_matrikulaere_forhold.ejerlav

**Comment by mapcentia** [comment]
Ejerlav er på nu

**Comment by Nyborg1** [comment]
Det er rigtig fint - takker
