### ISSUE TITLE
Extention  "ejendom"

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#15]
Hvad skal der til for at vi kan få "ejendom" til at virker

Tue skrev d. 4/8 i mail hvordan EjdExplorer kan startes for at flere matrikler op.

VIDI leverer denne url når den har fundet ejendom
**tlexpl**://?m=411153,2o

Det er kun een af de fundne matrikler.

Ejdexplorer starter ikke når der klikkes på knappen.

Hvad skal der skrives i windows-registry for at få den til det?

**Comment by Nyborg1** [comment]
Tue fra LIFA skrev dette i en mail:
Hej Peter

Tlexpl peger på TLExplorer og ikke EjdExplorer.

VIDI skal returnere ejdexpl og så er syntaksen lidt anderledes. Der skal vælges mode og så skrives matrikelnummer lidt anderledes – se mit eksempel fra d. 4. herunder.

EjdExplorer henter alle ejendomme på de matrikler den fodres med og derved alle matrikler de ejendomme består af. Så på den måde behøver EjdExplorer ikke kaldes med alle matrikler ejendommene består af. Du skal dog tage stilling til følgende scenarie

Brugeren trykker på matrikel 1a – Her ligger ejendom 100, som bliver slået op i EjdExplorer.
Ejendom 100 består også af matrikel 2a – den kommer automatisk med da det er samme ejendom
På matrikel 2a ligger også en anden ejendom 101 – den kommer ikke med.

Hvis ejendom 101 skal med generelt, så skal VIDI selv finde ud af hvilke ”ekstra” matrikler den også skal starte EjdExplorer med eller også skal den ændres til at kalde med geometri. Jeg ville dog mene at brugeren ikke behøver få ejendom 101, når den ikke ligger på den valgte matrikel.

**Comment by Nyborg1** [comment]
Navne forvirring:
Vi har slet ikke lisens til LIFA´s TLExplorer i Nyborg

EjdExplorer starter ikke når der klikkes på knappen.
Fordi det er et TL-Explorer-modul. 👎

**Comment by mapcentia** [comment]
Jeg er ikke helt sikker på, hvad det er der skal laves?

**Comment by Nyborg1** [comment]
:-)
