### ISSUE TITLE
Print - medtag makering af polygoner

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#16]
Er det muligt at få markeringer fra 'Søg' eller 'Info' med på print.

**Se Issue nr 1 i brugergruppens Github**
[Link](https://github.com/gc2vidi/Udvikling-og-vedligeholdelse/blob/master/001:%20Vidi%20moduler%20skal%20kunne%20undlade%20at%20trigge%20deaktiveringsevents.md)

**Comment by mapcentia** [comment]
De vil faktisk komme med, hvis de ikke blev slukket når Print vælges. Så er lige præcis issue 1. Jeg vil tage fat på det - det er også på tide

**Comment by mapcentia** [comment]
Issue 1 er ikke nok her, da Info-modulet er et "aktivt" modul, som vil sige, at det aktiverer klik-i-kortet og tegneværktøjer. Derfor skal det slås fra hvis man tænder et andet aktivt modul. Men jeg har nu lavet det sådan, at info-klik-markeringer er "sticky", så de forbliver i kortet efter modulet er slukket. Man skal nu aktivt slette markeringer med "ryd-kort" værktøjsknappen. Jeg lader dette issue være åbnen indtil jeg har lavet en ny version og rullet ud.

**Comment by mapcentia** [comment]
Så er ny version rullet ud
