### ISSUE TITLE
Ny version 2022.9.0

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#17]
Opgradering til ny version = 2022.9.0

**Comment by mapcentia** [comment]
GC2 er nu 2022.8.1 og Vidi 2022.9.1

**Comment by Nyborg1** [comment]
Jeg kan ikke logge ind på [](https://gc2.nyborg.dk/dashboard/sign-in)
Er password blevet nulstillet?
Jeg plejer at logge ind med denne *nyborg_gis*

**Comment by mapcentia** [comment]
Det skulle du kunne nu. Backups fyldte disken og sessionen kunne ikke skrives. Jeg har sat den til at retain 10 dage tilbage (fremfor 31)
