### ISSUE TITLE
Hastighed - optimering?

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#18]
Der er brugere som synes 'det' kører langsomt.
Vil det hjælpe at skrue op for ram eller andet på linuxserveren - nbwebgis?

**Comment by mapcentia** [comment]
Jeg vil tro, at det når der er fremmed tabeller involveret? I såfald vil ekstra ressourcer ikke hjælpe. Vi skal have afklaret hvor det  er det føles langsomt

**Comment by Nyborg1** [comment]
Ja jeg er også bange for at det er foreign tables der sløver det.
Men det er også langsommere når flere går på samtidigt - fx da jeg underviste 10 kollegaer
IT vil ikke bare give mere ram - men de har tilbudt at holde øje med ydelsen på både database-serveren og linux-serveren.

Hvad med tilecache-indstillingerne? Kan man sætte det op til at cache det helt i ned til zoomlevel 12 på forhånd?
Eller er det først når brugerne selv zoomer ind at der dannes tile-cache?

**Comment by mapcentia** [comment]
Typisk er alm. overlay kort ikke cached, da de oftes ændres, så cachen skal alligevel opbygges on-the-fly, som faktisk er langsommere end "live" kort. En bedre måde, at cache på er at bruge materialized views, men det kræver så noget mere opsætning. En ide er at omdøbe schemas med fremmed tabeller fx "dkjord_geofyn_nb" til "dkjord_geofyn_nb_f" og så oprette det igen med mat views. Dvs. at "dkjord_geofyn_nb" kommer til at indeholde mat view udgaver af fremmed tabellerne. Det kan gøres med et script og efterfølgende skal config mv ikke ændres.

Vi kan prøve med et schema eller to for at se hvordan det virke

**Comment by Nyborg1** [comment]
Ok.  Kan vi teste med skemaet _matrikel_geofyn_nb_
fx er tabellen jordstykke_links meget langsom.

Hvis man viser den samme tabel direkte i geofyns VIDI går det meget hurtigere

**Comment by mapcentia** [comment]
Jeg har skrevet et script, hvor man angiver et schema og der bliver så skabt et nyt schema med suffix "matviews" hvor alle tabeller er oprettet som mat views med indeksering.

Jeg har kørt det på "matrikel_geofyn_nb", så der er nu et kaldet "matrikel_geofyn_nb_matviews"

**Comment by Nyborg1** [comment]
Jordstykker fra den nye skema matrikel_geofyn_nb_matviews virker meget meget hurtigere

**Comment by Nyborg1** [comment]
Hvornår refreches materialised views. Skal der laves en trigger til at starte den?

**Comment by Nyborg1** [comment]
Under opdatering i går tror jeg at det gjorde hele det interne site ustabilt!
