### ISSUE TITLE
Vinterkort - opsætning

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#20]
**Opgaver løses asap - eksternt site skal være færdig d. 14/10** 
1. Intern vinter-config bruger den generelle interne config
skema = _05_07_snedrydning
Suppleret med projekt=vinter-intern

2. Ekstern vinter-config
kun  skema = _05_07_snedrydning
udbygges først senere med andre tabeller

Se Wiki-dokumentation:
https://github.com/Nyborg1/nyborg_gis/wiki/Kort.nyborg.dk

**Comment by mapcentia** [comment]
@Nyborg1 Sync er nu kørt, så _05_07_snedrydning er at finde på ekstern site
