### ISSUE TITLE
Title på Eksternt vinterkort

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#21]
Hvordan får jeg fjernet teksten :
**Powered By MapCentia \ Styrelsen for For Dataforsyning og forenkling**
Som står nederst på siden.
Kan jeg selv skrive:
**Vinterkort 2022/2023 Nyborg Komune**

**Comment by Nyborg1** [comment]
Er det en css-fil som kan tilrettes / placeres så jeg kan rette i den

**Comment by mapcentia** [comment]
Lige den tekst er fastsat for alle instancer af Vidi - dvs. at den kan ændres, men det slår igennem på alle Vidi instancer.

Man kan ikke ændre gennem CSS, men der er lavet en config indstilling, hvor man kan køre en JavaScript funktion, når Vidi starter op. Gennem den kan man ændre indhold:

`"initFunction": "function(){$('.leaflet-control-attribution').html('Vinterkort 2022/2023 Nyborg Komune')}"`

Jeg har lige sat ind her: https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_vinter_63344e3c4b704352182687.json

Men vi burde nok lave attribution teksten som en rigtig config indstilling

**Comment by Nyborg1** [comment]
Det er fint at det nu er ændre på vinterkortet. Er det alle Nyborgs VIDI-instanser eller er det alle mulige andre VIDI-instanser?. Jeg synes at du skal fjerne **Styrelsen for For Dataforsyning og forenkling** .
De ændrer navn hele tiden - og vi behøver ikke nogen at reklamere for andre. Copyright er ikke noget jeg vil gå op i :-)

**Comment by mapcentia** [comment]
Det er gennem config'en, så det er kun når man starter Vidi med den config at den ændres.

Attribution består af to dele:

"Powered by MapCentia" og den anden kommer fra baggrundskortenes opsætning.

Den først er en setting, der kan ændres. Fx har Kerteminde et lille byvåben efterfulgt af "Kerteminde Kommune".

Så hvad skal der stå i den første del? "Nyborg Kommune"?

Skal attribution fra baggrundskort fjernes?

**Comment by Nyborg1** [comment]
Kan du indsætte denne fil med Nyborgs byvåben.  Den kan omdøbes til *.ico
![NybKom-logo_rgb-transperent](https://user-images.githubusercontent.com/95336810/196143360-d6545e92-0f78-40b0-98c0-e395490d5e1b.jpg)

**Comment by Nyborg1** [comment]
Det ser fint ud på skærmdump - men jeg kan ikke se det i min browser :-) 
Hvis vi også vil have det andre steder end grundsalg. Hvor sættes det så ind?

**Comment by mapcentia** [comment]
@Nyborg1 initFunction bliver kun fyret af, når Vidi har loadet alt. I default baggrundskort er der en intern URL, som ikke virker på ydersiden:

```json
 [
        {
            "type": "wms",
            "url": "https://api.dataforsyningen.dk/orto_foraar_DAF?token=0e2dd7a0ee145e0993dfcb4376e18f1a",
            "layers": [
                "geodanmark_2022_12_5cm"
            ],
            "id": "Seneste_luftfoto_matr_adr_vej",
            "name": "Luftfoto, matr.nr og adresser",
            "description": "Ortofotos anvendes til ajourføring af de topografiske grunddata. Optagelsestidspunkt for ortofotos er om foråret før løvspring.",
            "attribution": "GeoDanmark",
            "minZoom": 12,
            "maxZoom": 19,
            "maxNativeZoom": 19,
            "transparent": true,
            "overlays": [
                {
                    "type": "wms",
                    "url": "https://api.dataforsyningen.dk/forvaltning2?token=eaca82e1cb411d78e841c7eba8ec1bbc",
                    "layers": [
                        "Vejnavne_basiskort",
                        "Stednavne_basiskort",
                        "Husnummer",
                        "Matrikel",
                        "Matrikel-foreloebig",
                        "Matrikel-tekst"
                    ],
                    "id": "Vejnavne_husnr_ortofoto_matr_nr",
                    "transparent": true,
                    "format": "image/png",
                    "maxZoom": 26
                },
                {
                    "type": "gc2",
                    "id": "_01_04_matrikulaere_forhold.ejerlav",
                    "db": "nyborg_gis",
                    "host": "https://gc2.nyborg.dk"
                }
            ]
        }
]
```
Den sidste `host` skal være den eksterne host: https://nyborg.admin.gc2.io før det virker på ydersiden.

**Comment by Nyborg1** [comment]
ok
