### ISSUE TITLE
VIDI-projekter på eksternt site - forsvundet!

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#23]
Alle projekter dannet med subusers er forsvundet - siden i går.
Nogle Tokens virker stadig - andre virker ikke.

Subusers er oprettet særskilt på https://nyborg.admin.gc2.io/dashboard/

Projekterne er dannet med subusers i VIDI

**Comment by mapcentia** [comment]
Hvor er projekter oprettet (ekstern eller intern)?
Paste lige en token ind, som ikke virker

**Comment by Nyborg1** [comment]
Det er de eksterne projekter som er væk..  Jeg har oprettet et enkelt nyt projekt.
Token følger

**Comment by Nyborg1** [comment]
eyJ0aXRsZSI6IlZpbnRlcjIwMjIiLCJhbm9ueW1vdXMiOmZhbHNlLCJzbmFwc2hvdCI6ZmFsc2UsImRhdGFiYXNlIjoibnlib3JnX2dpcyIsImhvc3QiOiJodHRwczovL2tvcnQubnlib3JnLmRrOiIsInVzZXJJZCI6InRlc3RfYnJ1Z2VyIiwiaWQiOiJzdGF0ZV9zbmFwc2hvdF82YTlhZmY1MC00YTA4LTExZWQtOGU1Zi0zYmJkZTFkNWNhNTkiLCJjcmVhdGVkX2F0IjoiMjAyMi0xMC0xMlQwODozMjozMi43MDlaIiwidXBkYXRlZF9hdCI6IjIwMjItMTAtMTJUMDg6MzI6MzIuNzA5WiIsImNvbmZpZyI6Ii9hcGkvdjIvY29uZmlndXJhdGlvbi9ueWJvcmdfZ2lzL2NvbmZpZ3VyYXRpb25fdmludGVyXzYzMzQ0ZTNjNGI3MDQzNTIxODI2ODcuanNvbiJ9
