### ISSUE TITLE
Fejl ved åbning af EjdExplorer

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#3]
ServiceID kommer ikke frem Ejdexplorer åbner bare men har ikke nogen adresser med.  Link fra VIDI "ejdexpl://?mode=merge&LIFAExternalIntegrationServiceID=undefined"
EjdExplorer åbner fint hvis jeg i browser  skriver ejdexpl://?mode=merge&LIFAExternalIntegrationServiceID=3340849

**Comment by mapcentia** [comment]
Dette ser ud til at være en bug i LIFAs  LIFAExternalIntegrationServiceREST

**Comment by mapcentia** [comment]
Efter vi skiftede til HTTPS ryger alt trafik gennem en Service Worker og det gør åbenbart noget ved LIFAExternalIntegrationServiceREST. Jeg sætter Vidi op til at kalde servicen uden om Service Worker.

**Comment by Nyborg1** [comment]
Det virker stadig ikke. Samme problem efter at cache er slettet og browser genindlæst

**Comment by mapcentia** [comment]
Der skal bygges ny Docker container, som skal deployes. Det er gjort nu. Cache skal ikke slettes manuelt - det gør Vidi selv, når der refreshes efter en update.
