### ISSUE TITLE
Indlejrede kort fejler

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#30]
Fejlsøgning:

1. Cookie policy er måske ændret?
2. Skal Token fornyes - når temaer slettes eller fornyes på sites?
3. Nye tokens virker på kort.nyborg.dk før eksport?

Ad 1
Kan man bruge data-vidi-no-tracking="true" til at undgå cookies
![cookie_fejl_på_embed](https://user-images.githubusercontent.com/95336810/200944552-62b3bbd4-3463-4f11-a213-adef9af39f54.png)

Ad 2
Nye lag-tabeller er tilføjet og andre er fjernet. De er fx brugt  i grundsalg og vinter - konfigurationerne.
Skal token fornyes hver gang dette sker

Ad 3
Udfordring hvis de projekter, der er skabt internt, vidi.nyborg.dk først er tilgængeligt eksternt på kort.nyborg.dk
Kan der udvikles en metode til at publicere/eksportere så man ikke vente på den natlige synkronisering

**Comment by mapcentia** [comment]
Ad 1. Dette skulle nu være løst.

**Comment by Nyborg1** [comment]
Der er dukket en fejl mere op på et andet indlejret kort.
Noget med https!
![image](https://user-images.githubusercontent.com/95336810/201117033-7bc0c052-c6e7-4cdf-b76e-7217f151917e.png)

**Comment by mapcentia** [comment]
Token er lavet på **http**://vidi.nyborg.dk og ikke **https**://vidi.nyborg.dk og browseren blokkere kald mellem https og http

Jeg kan se, at det er en fejl i opsætningen i GC2, den starter Vidi på http og ikke https. Det får jeg rettet.

**Mulige fikses**

Ved indlejring kan du sætte:

`data-vidi-host="https://vidi.nyborg.dk"`

Så den altid bliver tvunget over på https.

Ellers skal du kalde over https://vidi.nyborg.dk og genskabe token, ved at opdatere dit projekt.

**Comment by mapcentia** [comment]
Det med login er en fejl, som jeg ikke har set før. Du skulle gerne kunne logge ind på den eksterne uden dette sker.

Editering fungerer også på den eksterne, men data bliver jo overskrevet hver nat. Nogle klarer det ved at have en anden database, som kun eksisterer på ydersiden og denne bruger de så til editering.
