### ISSUE TITLE
Print virker ikke på vidi.nyborg.dk

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#32]
Det er ikke muligt at danne pdf eller png fra nogen af Konfigurationerne.
Fejlmeddelelse i browser:
_Cannot GET /tmp/print/png/undefined.zip_

**Comment by mapcentia** [comment]
Jeg er ved at opdatere Vidi - det er noget underliggende software, som skal opdateres

**Comment by Nyborg1** [comment]
ok :-)

**Comment by mapcentia** [comment]
Jeg har problemer med min VPN forbindelse - jeg får at vide "Your account is disabled", men jeg var på i går. Kan du tjekke  det? Mit user er: MapMartin

**Comment by Nyborg1** [comment]
It afdelingen har sikkert ændret sikkerheden.
Jeg prøver at checke det i morgen

**Comment by Nyborg1** [comment]
Kan du stadig ikke få vpn-forbindelsen til at virke

**Comment by mapcentia** [comment]
Jeg har adgang og Vidi er opdateret, så print virker igen
