### ISSUE TITLE
Ekstern WFS til NFS

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#37]
NFS - Nyborgs forsyning skal have adgang til data.

Vi tester med tabellen _13_02_vandforsyning.vandvaeksdistrikter som er overført til nyborg_gis via ogr2ogr
vandvaeksdistrikter er tagget med _borgerkort01 + internt
Skema "_13_02_vandforsyning" er tilføjet whitelist

Sub-user: usr/pwd
Samme user oprettet internt https://gc2.nyborg.dk/
og eksternt https://nyborg.admin.gc2.io/og ekstern nyborg.admin.gc2.io/

WFS-url tilgængelige tabeller per skema
https://gc2.nyborg.dk/admin/nyborg_gis/_13_02_vandforsyning/25832

Hvordan kan jeg give NFS adgang?  Hvorfor står der **admin** i url ?

Når data bliver først eksporteret til gc2.io i aften er det svært at teste!!!  Har du tænkt over hvordan vi udvikler mulighed for at smidiggøre proces?

**Comment by mapcentia** [comment]
Korrekt WFS/WMS URL: https://nyborg.admin.gc2.io/ows/nyborg_gis/_13_02_vandforsyning/

**Comment by Nyborg1** [comment]
Har du et script som kan danne en liste med alle tabeller?
Er der en måde at tilføje user/pwd?

**Comment by Nyborg1** [comment]
Jeg kan ikke få wfs til at svare - hverken i browser eller qgis.
Er du sikker på at det er samme url?

**Comment by Nyborg1** [comment]
Kan du hjælpe med disse

VIDI – wfs til vandværker og distrikter
https://nyborg.admin.gc2.io/ows/nyborg_gis/wfs/_13_02_vandforsyning/
_13_02_vandforsyning.vandvaerksdistrikter
_13_02_vandforsyning.vandvaerker

VIDI – wfs til rotter aktive fra DriftWeb
https://nyborg.admin.gc2.io/ows/nyborg_gis/_09_miljoebeskyttelse


Spildvandsplan (som også findes på plandata.dk)
https://nyborg.admin.gc2.io/ows/nyborg_gis/_06_spildevandsplan
_06_spildevandsplan.spildevandsomr_2018

**Comment by mapcentia** [comment]
@Nyborg1 Der er noget i vejen med udskrivningen af MapFiles, som sker med sync om natten. Jeg har lige gjort det manuelt og så virker det. Jeg afprøver den automatiske procedure nu, så der kan være, at der kommer udfald.

Schemaet _06_spildevandsplan findes ikke på ydersiden?

**Comment by mapcentia** [comment]
Dette skulle nu være fikset. Det var en forkert extent, der blev sat i WFS/WMS, som ikke omfattede objekterne. Derfor virkede WFS requests men var tomme

![image](https://user-images.githubusercontent.com/3850918/213176809-afc7beb8-9ff7-49ba-9950-76b1d308df86.png)

**Comment by Nyborg1** [comment]
Hej Martin 
Hvorfor kommer der fejl efter kald med denne url i en browser? [](https://nyborg.admin.gc2.io/ows/nyborg_gis/_13_02_vandforsyning/?request=Getcapabilities&service=wfs&crs=25832)

OWS kan bruges til både wms og wfs i QGIS
[](https://nyborg.admin.gc2.io/ows/nyborg_gis/_13_02_vandforsyning/ )
Men jeg er ikke sikker på at Forsyningsselskabets system forstår det?

**Comment by mapcentia** [comment]
Den første URL giver ikke fejl hos mig?

"Grund-url'en" til WFS og WMS er ofte den samme. Det er klienten (fx QGIS), der sætter hhv. WMS og WFS parametrene på.

**Comment by Nyborg1** [comment]
Tak for kvalitetssikring :-)
Den første url giver ikke fejl - bare en række advarsler om at metadata mangler.
Jeg kontakter Forsyningsselskabet igen
