### ISSUE TITLE
Ekstern WMS til NFS

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#38]
NFS - Nyborgs forsyning skal have adgang til specifikke tabeller.

WMS url viser alle tilgængelige tabeller
https://nyborg.admin.gc2.io/mapcache/nyborg_gis/wms
Kan det styres så de kun får adgang til at se specifikke tabeller / skemaer?

**Comment by mapcentia** [comment]
Det er tile cache URL'en, som primært bruges til WMTS, Google XYZ og lign. bruge denne:

Korrekt WFS/WMS URL: https://nyborg.admin.gc2.io/ows/nyborg_gis/_13_02_vandforsyning/
