### ISSUE TITLE
Data kan ikke vises på eksterne sites

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#39]
Der vises ingen eller kun få data på den eksterne konfiguration:

Fx konfiguration = ekstern
https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_kortnyborg_62f4e0f32ccda467979749.json

Umiddelbart er data kopieret rigtigt ud til den eksterne database.
Kan du se i nogle logfiler hvad der går galt? 

Dette hænger sammen med 2 foregående issues wms/wfs adgang til Nyborg Forsyning

**Comment by mapcentia** [comment]
@Nyborg1 Prøv nu. En internt IP adresse var blevet skiftet og så kunne der ikke forbindes til Geo Fyn database pga. firewall regler.

**Comment by Nyborg1** [comment]
Tak Matin.
Jeg tror at det virker nu. Heldigvis berørte det ikke de 2 konfigurationer jeg har i drift.
vinter og grundsalg.  Her benyttes vist ikke datasæt fra Geo Fyn
