### ISSUE TITLE
Print PDF fra ekstern VIDI

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#40]
**Det er ikke muligt at danne pdf eller png på det eksterne VIDI**

https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_kortnyborg_62f4e0f32ccda467979749.json#Basis_kort/11/10.6485/55.3033/_00_grundkort.passepartout

Fejl i browser
Cannot GET /tmp/print/png/undefined.zip

Det virker fint på vidi.nyborg.dk

**Comment by mapcentia** [comment]
Er fikset - noget med at Chromium ikke var installeret efter seneste update
