### ISSUE TITLE
WMS - transparency i openlayers

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#41]
Jeg har problemer med at få wms-lag fra VIDI til at være transparente.

Jeg tror at VIDI udstiller dem rigtigt - men når lag åbnes i OpenLayor. Så kan man ikke se igennem flere wms-lag.
eks på kald af wms.  Hvad kan man skrive i stedet for **transparent: true**

new OpenLayers.Layer.WMS("Rosy veje", ["https://nyborg.admin.gc2.io/ows/nyborg_gis/_05_veje_trafik"], {
    layers: "_05_veje_trafik.vgeo11admsection",
    format: 'image/png'
}, {
    isBaseLayer: false,
    visibility: false,
    **transparent: true,**
    globalopacity: 0
})

**Comment by Nyborg1** [comment]
Der kommer en hvid baggrund - ligegyldigt hvad jeg gør.
Vi bruger det i Sweco´s DriftWeb. Deres support kan ikke hjælpe

**Comment by mapcentia** [comment]
Prøv lige

new OpenLayers.Layer.WMS("Rosy veje", ["https://nyborg.admin.gc2.io/ows/nyborg_gis/_05_veje_trafik"], {
layers: "_05_veje_trafik.vgeo11admsection",
format: 'image/png',
transparent: true,
}, {
isBaseLayer: false,
visibility: false,
globalopacity: 0
})

**Comment by Nyborg1** [comment]
Det virker :-) Tak Martin
