### ISSUE TITLE
skråfoto virker ikke efter SDFI har opdateret løsning

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#42]
Jeg kan se at  issue er fixed.
https://github.com/gc2vidi/Udvikling-og-vedligeholdelse/issues/9

Hvordan får vi det til at virke i Nyborg i fx
https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_drift_63c91a8be08d1318765497.json#Basis_kort/12/10.7767/55.3023/

**Comment by mapcentia** [comment]
Dette er fikset i denne opdatering jeg lige har rullet ud

**Comment by Nyborg1** [comment]
Tak Martin

**Comment by Nyborg1** [comment]
Skråfoto åbner med billeder fra 2019 - og ikke med de nyeste billeder!
Er det noget der kan fikses?
![skråfotoextention](https://github.com/Nyborg1/nyborg_gis/assets/95336810/61d370af-a8cc-477a-b6d8-30b4dac8aa6b)

Samme problem i både gammel og ny VIDI
