### ISSUE TITLE
Fejl på eksport til eksternt setup (io)

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#44]
Der mangler at blive opdateret noget!!

Problem med at eksportere noget til
nyborg.admin.gc2.io/admin/nyborg_gis/_00_grundkort

Tabellen "passepartout" (kommunegrænsen) bliver ikke vist korrekt eksternt. 

Jeg har rettet visningen manuelt i den interne løsning  gc2.nyborg.dk efter jeg opdagede fejl med import af qgis-projekt - hvor tabellen kom med ved en fejl.

Kommunegrænsen bliver brugt mange steder !  
Det ser meget grimt ud med en lilla sørgerand :-(

![2023-02-22 08_26_20-Window](https://user-images.githubusercontent.com/95336810/220551821-bb38dea1-54ce-47be-a90e-2fec7bf68e98.png)

Korrekt visning 

![2023-02-22 08_27_02-Window](https://user-images.githubusercontent.com/95336810/220551868-247b3a3b-dc9a-4c1c-ae8d-36a3dace7275.png)

**Comment by mapcentia** [comment]
@Nyborg1 Den er også lilla i den interne. Den anvender et QGIS projekt

**Comment by Nyborg1** [comment]
Ok Det er så en fejl. Hvordan fjerner man tematiseringen fra denne tabel

**Comment by mapcentia** [comment]
Man fjerner indholdet i WMS Source:
![image](https://user-images.githubusercontent.com/3850918/220620843-e3e030f4-d9ea-4c88-99d5-25a124b9b173.png)

**Comment by Nyborg1** [comment]
Tak Martin.
Det var nemt at rette. Men det er svært at håndtere at et lag i et tilfældigt  qgis-projekt ødelægger visningen så mange steder.
Jeg vil prøve at beskrive en best practice for tematisering med qgis-projekter
