### ISSUE TITLE
Adressesøgning fejler

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#45]
Adressesøgning fejler både i den interne og den eksterne vidi

- nogle adresser mangler - fx **Assensvej 46**

Sidst vi havde dette problem var efter opdateringen af gc2/vidi  lige efter nytår

**Comment by Nyborg1** [comment]
Assensvej kan igen søges - både internt og eksternt

**Comment by Nyborg1** [comment]
Geopartner tjekker via en indeksering om adressehøst fra DAWA går godt. De havde også observeret at der manglede adresser

**Comment by Nyborg1** [comment]
Der mangler adresser i adresse-søgningen igen.
**Poppelvej**  har ingen hits.
Vil du kigge på det ?

**Comment by mapcentia** [comment]
@Nyborg1 Prøv lige igen. Monitor-systemet meldte om fejl, men inden jeg nåede at gøre noget, meldte det ok igen.
