### ISSUE TITLE
skolegis

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#47]
Hvad skal der til for at implementere dit gamle setup skoleGIS i Nyborg eller hos GeoFyn?

Kender du løsningen fra Hjørring
https://iod.hjoerring.dk/koersel

Migle Salkuviene fra Hjørring Kommune nævnte at du måske kunne opgradere deres løsning

**Comment by mapcentia** [comment]
Der skal laves et rutenetværk ved brug af pgRouting (Postgres extension). Jeg har før anvendt GeoDK vejmidter, hvor trafikveje bliver påført en stor modstand, så stier og mindre veje bliver prioriteret.

Mit gamle setup er en Vidi extension målrettet sagsbehandlere, så der skal nok tilpasses noget, hvis målgruppen er borgere.

**Comment by Nyborg1** [comment]
udvikling foregår på [https://github.com/mapcentia/skolevej](url)
