### ISSUE TITLE
Intern VIDI fejler

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#48]
Der er noget helt galt på de interne sider
Måske er det noget med sikkerhed. https
Browser skriver NET::ERR_CERT_DATE_INVALID

Nedenstående konfiguration er den der bruges til byggesagsbehandling
https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_byggesag_62d91f5de8e25661721514.json#

De eksterne sites fungere fint

**Comment by Nyborg1** [comment]
"Denne server kunne ikke bevise, at den er vidi.nyborg.dk, da sikkerhedscertifikatet udløb inden for det seneste døgn. Dette kan skyldes en fejlkonfiguration, eller at en hacker har opfanget din forbindelse."

**Comment by Nyborg1** [comment]
Jeg har ikke længere adgang til gc2 dashboard

gc2.nyborg.dk/dashboard/sign-in

**Comment by mapcentia** [comment]
@Nyborg1 Cert er udskiftet. Det kan være at browser lige skal genstartes

**Comment by Nyborg1** [comment]
Tak Martin
