### ISSUE TITLE
fejl ved editering og tabelvisning

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#49]
Kort og liste med 'grundejerforeninger' skal vises på ekstern hjemmeside.
Er det en udfordring at have editering samtidig med tabelvisning?

Det ser ud til kun at fungere hvis der i Meta er sat flueben i "Disable feature info"
[https://gc2.nyborg.dk/admin/nyborg_gis/_01_fysisk_plan_og_naturbeskyt]
![grunejerforeninger](https://github.com/Nyborg1/nyborg_gis/assets/95336810/1d7ca152-bce4-4583-a823-d153b193ba15)

Hvad er det  går galt her?
![2023-05-23 08_41_46-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/e99032f5-8517-4757-8080-5cd78509d152)

**Comment by mapcentia** [comment]
Jeg har lige opdateret GC2 og Vidi til nyeste, men jeg tror ikke, at det er en egenlig fejl du oplever. Som jeg kan se, er featuren du klikker på under editering (Afventer login). I den tilstand bliver al tekst URL encoded, så det slipper gennem netværket uden at blive ændret. Info-pop-up viser den encoded tekst. Så snart den igangværende editering er slut (gemmes på serveren eller den fortrydes) ser teksten rigtig ud igen.
