### ISSUE TITLE
Geofyn tematisering for plandatadk_geofyn_nb mangler

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#5]
Tematiseringen i gruppen "planlægning" er væk og skal hentes igen!

**Comment by mapcentia** [comment]
Af gruppede lag mangler tematisering i disse;

Lokalplandelområde
Lokalplandelområde - forslag
Kommuneplantillæg - forslag
Kommuneplanramme
Kommuneplanramme - vedtaget

Men de mangler også i Geofyn's nyborg database. Så jeg tænker ikke, at de er forsvundet

**Comment by Nyborg1** [comment]
Nu henter vi disse tabeller fra cowi ePlan.
Endvidere har jeg skrevet til Geofyn og gjort dem opmærksom på fejlen - og bedt dem fortælle hvis de bruger temaer fra et andet skema til visning af data fra plandata.dk
