### ISSUE TITLE
Fejl i grundsalgopsætning

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#51]
Højgårdsløkken 32 vises ikke i kortet!

Hvad er ideen med view grundsalg_label?
Det bygger på tabellen 'grundslag_grund_20221220' - men det er 'grundsalg_grund' benyttes.
Skal det ikke ændres

Der er fejl i 'grundsalg_grund' 
![2023-06-02 09_13_19-GC2 Admin – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/595f9c62-86b0-41dd-a8ac-3a3ad6ac6774)

Dette gør at det ikke umiddelbart er muligt at rette i tabellen via GC2 admin-konsollen

**Comment by Nyborg1** [comment]
![image](https://github.com/Nyborg1/nyborg_gis/assets/95336810/eec478b0-c0d7-4b3b-9817-86c9527f1dc4)
Højgårdsløkken 32 vises ikke i kortet!

**Comment by Larsklindt** [comment]
Det er løst. det viste sig at der for Højgårdsløkken 32, var sat 'Højgårdsløkken' som grundsalgsområder og ikke det korrekte 'Højgårdsløkken, 5540 Ullerslev', hvor de andre grundsalgsområder var tilknyttet. Det er rettet på den interne løsning, og bør slå igennem i morgen, når data replikeres i nat.

**Comment by Nyborg1** [comment]
Tak skal du ha. Lars
