### ISSUE TITLE
Opgradering af VIDI - inden endelig udrulning til VIDI-brugere i Nyborg

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#54]
Er det muligt at påbegynde en opdatering af VIDI

**Comment by Nyborg1** [comment]
Hvis den nye version af VIDI er testet og i drift andre steder - så må du gerne påbegynde en opgradering i Nyborg.
Bemærk at jeg har en hård deadline der hedder 15/10 - alternativt skal vi vente helt til påske næste år

**Comment by mapcentia** [comment]
Jeg vil starte med den eksterne. Det er fordi modulet brev-felt endnu ikke er testet med Ny Vidi, men det bruges jo ikke på den eksterne. Og deadlinen handler snerydning på den eksterne ikke?

**Comment by Nyborg1** [comment]
Ja - det er kun det eksterne vintervedligehold der er deadline på.
Er det muligt at køre noget test på de nye setup?
Der er sikkert andre afhængigheder vi skal trykteste fx grunde til salg, som Geopartner har hjulpet lidt med

**Comment by mapcentia** [comment]
Test Vidi:

https://nyborg-test.vidi.gc2.io/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_vinter_63344e3c4b704352182687.json

**Comment by Nyborg1** [comment]
Det ser godt ud Martin - tak.
Vi er allerede i gang med at teste.

**Comment by Nyborg1** [comment]
Der er en fejl når man bruger filter-funktionen
![2023-09-14 09_50_02-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/c300c188-aab2-4ceb-a321-0a274b6d35d6)

**Comment by mapcentia** [comment]
Hvad er fejlen? Er det det røde "!" ? Det betyder bare, at der er sat et filter

**Comment by Nyborg1** [comment]
:-)  Det er fint med den røde "advarsel"
Tror bare at jeg havde glemt at deaktivere / nulstille et andet filter. Det er ikke en fejl!

**Comment by Nyborg1** [comment]
Martin. Kan du maile mig url og login / password test-sitet, så jeg kan teste andre konfigurationer på 'nyborg-test.vidi.gc2.io'

Jeg har specifikt brug for at teste fx denne konfiguration, der bruges til grundsalg.
https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_grundsalg_634e716665895965999101.json#osm/17/10.6678/55.3657/_13_06_02_salg_af_jord.grundsalg_grund 

Tabellerne der bruges ligger i skemaet
nyborg_gis/_13_06_02_salg_af_jord

**Comment by mapcentia** [comment]
Det er kun Vidi, der har en test-version. Så man skifter blot `vidi.nyborg.dk` i url'en ud med `nyborg-test.vidi.gc2.io`. Fx ovenstående url bliver til

`https://nyborg-test.vidi.gc2.io/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_grundsalg_634e716665895965999101.json`

Man kan logge ind med samme brugere og passwords.

**Comment by Nyborg1** [comment]
ok - med adgang og samme login.

Er det rigtigt forstået at de projekter og tokens fra det interne VIDI kan bruges i de indlejrede kort.?
Det er så bare en -div- der bestemmer hvilket site der vises.


![2023-09-15 12_01_22-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/72a29177-f658-4149-8034-61ff0600ae8c)

**Comment by Nyborg1** [comment]
Grundsalgsopsætning flyttes til nyt issue nr:

https://github.com/Nyborg1/nyborg_gis/issues/69

**Comment by Nyborg1** [comment]
Det lader til at der mangler et sikkerhedscertifikat 
testsitet kan ikke umiddelbart åbnes af andre en mig 
172.16.1.99:3000
Er det noget du kan lægge på eller skal jeg bestille IT-afdeling til noget
![2024-05-08 14_13_17-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/ce85be6d-c55a-4f72-b143-7bfb8192c11c)

**Comment by Nyborg1** [comment]
#

**Comment by Nyborg1** [comment]
#85
