### ISSUE TITLE
Cowi gadefoto

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#6]
brugernavn = Nyborg_Kommune
adgangskode = 3B9A08C5

**Comment by Nyborg1** [comment]
Hvad skal der tilføjes i konfiguration=intern?
Hvordan skal det skrives?
VIDI kommer med en blank skærm hvor der står at srid is undefined. Ser ikke ud som om den læser dette!


    "extensionConfig": {
        "streetView": {
            "Cowi gadefoto ": "https://cmv.cowi.com/?u=Nyborg_Kommune&p=3B9A08C5&project=DDG Nyborg Kommune&maximize=DDG Latest&ssTrigger=SINGLE_CLICK&srid=4326"
        }
    },

**Comment by mapcentia** [comment]
Det korrekte er:

``` 
"extensionConfig": {
    "streetView": {
        "cowi": "https://cmv.cowi.com/?u=Nyborg_Kommune&p=XXXXX&project=DDG Nyborg Kommune&maximize=DDG Latest&ssTrigger=SINGLE_CLICK&"
    }
},
```
