### ISSUE TITLE
Tematisering - Fejl ved upload af QGIS-projekter til GC2

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#60]
Tematisering vises ikke ved tematisering på ekstern VIDI
Indlæsning af *.qgs fra nye versioner af QGIS fejler.

Det virker når *.qgs projektet skabes i gammel QGIS-3.26

Issue hænger sammen med [Tematisering af "drift-konfiguration" vises ikke korrekt #59](url)

[vandlob_ny_332.qgs](https://github.com/Nyborg1/nyborg_gis/files/12437315/vandlob_ny_332.txt)
[vandlob_ny_326.qgs](https://github.com/Nyborg1/nyborg_gis/files/12437317/vandlob_ny_326.txt)

**Comment by mapcentia** [comment]
@Nyborg1 Så er det samme QGIS Server version, der findes på den interne og eksterne

**Comment by Nyborg1** [comment]
Hvilken version QGIS-server anvendes på det interne og eksterne site?
Det er stadig kun muligt at få QGIS-projekter i ældreversion til at vise tematisering på den eksterne site.

Vedlagte *.qgs fil er skabt i version QGIS v. 3.28.10 vises kun korrekt på det interne site (omdøb fra *.txt til *.qgs)
[vandlob_ny_328.txt](https://github.com/Nyborg1/nyborg_gis/files/12483461/vandlob_ny_328.txt)

Denne qgs kan uploades og virker også eksternt 
[vandlob_ny_326.txt](https://github.com/Nyborg1/nyborg_gis/files/12483484/vandlob_ny_326.txt)

**Comment by mapcentia** [comment]
Der anvendes 3.18. Men den eksterne var "hoppet" tilbage til 3.16 LTS, som har problemerne. Det skyldtes, at jeg havde opdateret den manuelt, men nu har jeg bygget en ny service, så den forbliver på 3.18.

Vi kan komme op på 3.28 LTS, når det grundlæggende software på GC2 serveren bliver opdateret. Det hænger sammen med en del andre opdateringer, men det kommer snart.
