### ISSUE TITLE
Style på markering / Highlight i VIDI 

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#61]
Highlight er rød og markering er stiplet rød
Kan markeringen ændres til stiplet blå? 
![2023-08-31 15_58_23-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/102633b9-f814-4f6c-901f-e5f35df61a91)

**Comment by mapcentia** [comment]
Ja, i GC2 `Meta > Tile settings > Selected` style kan der indsættes et style objekt.

```json
{
    "color": "blue"
}
```

![image](https://github.com/Nyborg1/nyborg_gis/assets/3850918/bae30da0-8980-4177-a6e3-3a822cef8980)

Se her for flere egenskaber:

https://vidi.readthedocs.io/da/latest/pages/standard/92_gc2_meta_information.html#tile-settings

**Comment by Nyborg1** [comment]
Jeg har nu prøvet at indsætte style blue i-meta for tlconnect.vw_tingbog_servitutter_udbredelse

Men så bliver det hele bare blåt og stiblet!  
Der er ingen forskel jvf billedet overfor

**Comment by mapcentia** [comment]
Skulle det ikke også være blåt og stiblet? Er det fordi det er et polygon-lag, som har en fill-color? Hvis der ikke skal være fill-color skal man sætte fill-opacity til 0:

```json
{
    "color": "blue",
    "fillOpacity": 0
}
```
