### ISSUE TITLE
Historiske adkomster mangler i tabel

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#62]
kolonne med et link til historiske adkomster i tabellen.

**Comment by Nyborg1** [comment]
Jeg kan godt se at den er tilføjet i 
tlconnect.vw_tingbog_adkomst.geom

Men det er denne tabel der er sat op i VIDI
tlconnect.matvw_tingbog_adkomst.geom

Er det meningen at begge tabeller skal vises i gui´en

**Comment by Larsklindt** [comment]
Hej Peter.

Jeg tror blot det handler om at vi skal have genbygget 'tlconnect.matvw_tingbog_adkomst' måske er den genbygget og feltet er her til morgen og det er dette materialized view, der skal bruges. Jeg kan hjælpe med at du kommer helt i mål, også med opsætningen i GC2.

Ring gerne, så aftaler vi nærmere.

**Comment by Nyborg1** [comment]
De historiske adkomster er ikke med i visningen hertil morgen
Jeg tror at der mangler noget i view-definitionen af tlconnect.matvw_tingbog_adkomst.geom

![2023-09-06 08_52_22-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/3889e89d-b802-4af1-9f3a-22360315064f)

**Comment by pederdk1** [comment]
Så er link til de historiske adkomster tilføjet i tlconnect.matvw_tingbog_adkomst

**Comment by Nyborg1** [comment]
Tak. kolonnen med link er nu med i VIDI

![2023-09-07 10_07_54-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/b9e1f69d-b537-49b6-8c90-657a1384b9d9)
