### ISSUE TITLE
Pdf-print fylder 2 sider

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#64]
Pdf- print kommer ud på 2 sider!  Det gælder alle papirstørrelser på det interne site.
![2023-09-11 12_55_39-0565a198-989e-4940-b043-a99e76dc9612 pdf – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/bdc4117b-de45-4600-8698-deff332df1a5)

https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_intern_623d925bf2a5a285566709.json

Det virker på det eksterne VIDI-site

**Comment by mapcentia** [comment]
Det var headeren, som var placeret for lavt. Nu er den placeret rigtigt
