### ISSUE TITLE
Ny VIDI - internt

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#66]
Inden den nye VIDI-gui tages i brug internt må du godt bruge nogle timer på at teste og fikse modulerne som anvendes her.
* Brevflet-knap og kald til LIFA- EjdExplorer
* Konfliktsøgning

**Comment by Nyborg1** [comment]
Kan du estimere hvad der skal til for at disse to moduler kan virke i den nye VIDI.
Måske Kristoffer eller Tino vil være med til at finansiere :-)

**Comment by mapcentia** [comment]
Konfliktsøgning vikrer i Ny Vidi

**Comment by Nyborg1** [comment]
Ok 
Så er det bare modulet "Brevflet og kald til LIFA-EjdExplorer som skal testes inden vi ka opgradere. Kan du sætte et internt testsite op?
