### ISSUE TITLE
WMTS-services til Datafordeler

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#68]
Tidligere hentede vi baggrundskort fra Dataforsyningen. De skal skiftes til Datafordelerens services.
Jeg kan godt få svar i browser og i QGIS på eksempelvis dette kald.

https://services.datafordeler.dk/GeoDanmarkOrto/orto_foraar_wmts/1.0.0/WMTS?username=xxxx&password=xxxx&service=WMTS&request=GetCapabilities

Men den virker ikke i GC2 - hvad er syntaxen?

Lige nu fejler mange af de gængse baggrundskort fx skærmkort og ortofoto)

**Comment by Nyborg1** [comment]
Fra konfiguration intern.

![2023-09-19 10_38_31-Window](https://github.com/Nyborg1/nyborg_gis/assets/95336810/bb8f1da3-aab5-4878-bfbf-25cff4480f2d)

**Comment by Nyborg1** [comment]
Ok - jeg har fået Datafordelerens wms til at virke.
Men deres WMTS-servise virker ikke i VIDI - eller?

**Comment by mapcentia** [comment]
Nej, WMTS er ikke understøttet.

**Comment by Nyborg1** [comment]
Hvordan får vi skærmkortet - fra Datafordeleren  til at virke i VIDI..  Read the docs henviser til Dataforsyningen - som pt ikke virker

**Comment by Nyborg1** [comment]
Kan skærmkortet komme med i din proxy
https://services.datafordeler.dk/Dkskaermkort/topo_skaermkort/1.0.0/wms??username=YAGUYJDYXS&password=Dataklovn_20&service=WMS&request=GetCapabilities

**Comment by mapcentia** [comment]
Jep:
 
"url": "/api/datafordeler/Dkskaermkort/topo_skaermkort/1.0.0/wms",
"layers": ["dtk_skaermkort"],

**Comment by Nyborg1** [comment]
takker  :-)
