### ISSUE TITLE
Grundsalg - ny version af  ekstern VIDI

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#69]
Test af opsætning af Grunde til salg i ny VIDI.
Fortsættes fra issue nr   https://github.com/Nyborg1/nyborg_gis/issues/54

![2023-09-22 09_52_15-Villagrunde, bolig og byggeri - Nyborg dk – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/a19cd1c4-6d00-4d09-a6cf-712a91071770)

**Comment by Nyborg1** [comment]
Token der bruges til Højgårdsløkken bliver på nyborg.dk fulgt af denne div: 
data-vidi-host="https://nyborg-test.vidi.gc2.io"

**Comment by Nyborg1** [comment]
Fejl 
- info er slået til "fandt ikke noget" 
- Der kommer kun én række med under kortet¨

Justeringer: 
fjern login med div?

**Comment by Nyborg1** [comment]
Konfiguration, der bruges til grundsalg.
https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_grundsalg_634e716665895965999101.json#osm/17/10.6678/55.3657/_13_06_02_salg_af_jord.grundsalg_grund

**Comment by Nyborg1** [comment]
Token og div:
--div data-vidi-token="eyJpZCI6InN0YXRlX3NuYXBzaG90XzQ4OWFjOTEwLTRlYzktMTFlZC1iZjhjLWZmYWYxMGVmYWQ5YiIsImhvc3QiOiJodHRwczovL3ZpZGkubnlib3JnLmRrOiIsInRpdGxlIjoiSMO4amfDpXJkc2zDuGtrZW4iLCJ1c2VySWQiOiJncnVuZHNhbGciLCJkYXRhYmFzZSI6Im55Ym9yZ19naXMiLCJzbmFwc2hvdCI6ZmFsc2UsImFub255bW91cyI6ZmFsc2UsImNyZWF0ZWRfYXQiOiIyMDIyLTEwLTE4VDA5OjQzOjEzLjE4NVoiLCJ1cGRhdGVkX2F0IjoiMjAyMi0xMi0wNlQwNjowOToyNy41MDNaIiwiY29uZmlnIjoiL2FwaS92Mi9jb25maWd1cmF0aW9uL255Ym9yZ19naXMvY29uZmlndXJhdGlvbl9ncnVuZHNhbGdfaGplbW1lc2lkZV82Mzk4NDYyYjM0MDQ0OTI5NTkxOTcwLmpzb24ifQ=="
data-vidi-use-config="true"
data-vidi-history="none"
data-vidi-layer="none"
data-vidi-legend="none"
data-vidi-background="none"
data-vidi-fullscreen="none"
data-vidi-about="none"
data-vidi-location="none"
data-vidi-signin="none"
data-vidi-host="https://nyborg-test.vidi.gc2.io">- div-

**Comment by mapcentia** [comment]
Login kan fjernes med enten:
- **data-vidi-signin="none"** i embed div
- **&sig=none** i URL

Tabellens højde styres gennem config. Den er pt. sat til kun 120 px:
```json
    "vectorTable": {
        "position": "bottom",
        "width": "30%",
        "height": "120px"
    }
```

**Comment by Nyborg1** [comment]
Synes ikke det virker
Div er sat til **data-vidi-signin="none"**
Se ovenfor

**Comment by mapcentia** [comment]
Det er nok fordi embed.js bliver hentet fra den "gamle" Vidi. Så efter skiftet vil det virke.

**Comment by mapcentia** [comment]
"fandt ikke noget" udløses af at Meta > "Disable feature info" er tjekket af. Det er en bug, som jeg kigger på.

**Comment by Nyborg1** [comment]
Det bliver svært at teste de 15 tokens inden skiftet, hvis det er den gamle embed.js der bruges.
Hvad med højden?  Jeg har ændret den til 320px - Kan den så først ses i morgen

**Comment by mapcentia** [comment]
Jeg har copy/pasted den nye embed.js kode ind i det gamle script, så de nye data-vidi attributter burde virke

**Comment by Nyborg1** [comment]
Vil du kigge på font og tekststørrelse i tabelvinduet?
Det er stadig dette kortelement vi tester  ["Højgårdsløkken" ](https://www.nyborg.dk/da/borger-og-selvbetjening/bolig-og-byggeri/vil-du-bygge/villagrunde-bolig-og-byggeri/)

Der er også et par tekster som ikke skal med ""Kort.nyborg"  og "Powered by..."


![2023-09-25 10_19_14-Villagrunde, bolig og byggeri - Nyborg dk – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/e19bf062-a04d-4471-8d09-e7543a1ec949)

**Comment by mapcentia** [comment]
- Bruge **data-vidi-brand="none"** for at fjerne "kort.nyborg.dk"
- Tabel-tekst er justeret gennem grundsalg.css
- I config'en **Grundsalg_hjemmeside** er der et internt kort i baseLayer > overlays. Det fungerer ikke på ydersiden og forhindre initFunction fra at køre, så attribution ikke bliver ændret.

**Comment by Nyborg1** [comment]
Er du klar til at skifte - nu?

**Comment by mapcentia** [comment]
@Nyborg1 Ja, der er skifte nu

**Comment by Nyborg1** [comment]
Fremover skal der kun bruges en konfiguration = "grundsalg_hjemmeside" 
Det ser ud til at virke!
alle grundsalgs-tokens er efterfulgt af -div- **data-vidi-signin="none"**
