### ISSUE TITLE
Externt site    Er kort.nyborg.dk' og  'nyborg.gc2.io' klar..

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#7]
Installation
Placering og systemsetup

**Comment by Nyborg1** [comment]
Martin vil kigge på setup af det eksterne site - det har højeste prioritet at jeg kan begynde at publicere nogle data eksternt!

**Comment by mapcentia** [comment]
Virker nu. Vidi eksempel: https://kort.vidi.gc2.io/app/nyborg/husdyr_geofyn_nb/

Jeg har lavet en test synkronisering med et par schemaer og det kører fint.

Bemærk, at den eksterne database hedder "nyborg" og ikke "nyborg_gis". 

GC2 Admin findes på: https://nyborg.admin.gc2.io/

**Comment by Nyborg1** [comment]
Tak Martin.
Jeg tror ikke at jeg har adgang til websitet og gc2-dashboardet endnu.
Hvilken bruger kan jeg logge ind med på den eksterne database.

**Comment by mapcentia** [comment]
Det er selvfølgelig denne url, der virker til ekstern Vidi:
https://kort.nyborg.dk/app/nyborg/husdyr_geofyn_nb/

**Comment by Nyborg1** [comment]
Jeg kan åbne url til det eksterne fra min private pc. Den siger endda at certifikat er ok.
https://kort.nyborg.dk/app/nyborg/husdyr_geofyn_nb/

På Nyborgs net / pc kan jeg ikke åbne kort.nyborg.dk 

Skal Nyborgs IT-afd installere certifikatet, skrive noget i firewall eller det noget jeg kan gøre i browserindstillingerne?

Jeg kan også logge ind på dashboard på det eksterne site
https://nyborg.admin.gc2.io/dashboard/

Navngivningen https://nyborg.vidi.gc2.io/  
Forvirrede mig lidt fordi det er meget tæt på navnet på det interne site https://vidi.nyborg.dk/

**Comment by Nyborg1** [comment]
Jeg vil gerne have styr på system-konfiguration!
Hvor er de filer, som styrer hvad og hvornår der kopieres?
Hvor er skal den liste med skemaer der kopieres ligge?

**Comment by mapcentia** [comment]
Den eksterne database hedder nu også "nyborg_gis" som den interne. Det gav nogle problemer i QGIS filerne at omdøbe den. Så man skal nu også logge på den eksterne GC2 med nyborg_gis

**Comment by Nyborg1** [comment]
Jeg kan ikke logge ind på dashboardet..   Har prøvet med flere passwords.
Kan du maile det eller skrive det i teams?

**Comment by mapcentia** [comment]
Er sendt på mail

**Comment by Nyborg1** [comment]
ok -  Det lykkedes.
Databasen hedder nyborg_gis på både intern og ekstern.  Men har forskelligt password :-)

**Comment by Nyborg1** [comment]
Men jeg kan stadig ikke få adgang til at se sitet. Hverken med  
https://kort.nyborg.dk/app/nyborg/husdyr_geofyn_nb/  eller
https://nyborg.vidi.gc2.io/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_byggesag_62d91f5de8e25661721514.json#Basis_kort/12/10.7767/55.3023/

Sidst nævnte virker eksternt

**Comment by mapcentia** [comment]
> Men jeg kan stadig ikke få adgang til at se sitet. Hverken med https://kort.nyborg.dk/app/nyborg/husdyr_geofyn_nb/ eller https://nyborg.vidi.gc2.io/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_byggesag_62d91f5de8e25661721514.json#Basis_kort/12/10.7767/55.3023/
> 
> Sidst nævnte virker eksternt

Det er det samme eksterne site de to URL'er peger på. Men det er 
https://kort.nyborg.dk/app/nyborg_gis/husdyr_geofyn_nb/ (/**nyborg_gis**/ ikke /**nyborg**/)

Det er noget med jeres interne DNS hvad angår kort.nyborg.dk. nyborg.vidi.gc2.io skulle gerne virke (Det gør det for mig, når jeg er på jeres netværk)

**Comment by Nyborg1** [comment]
Det virker nu - også internt.  
Min IT-afdeling har lavet en C-name internt DNS record
