### ISSUE TITLE
Ny VIDI - Grundejerforeninger

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#70]
Udløber af andre issue: 
[https://github.com/Nyborg1/nyborg_gis/issues/50](url)

[https://github.com/Nyborg1/nyborg_gis/issues/69](url)

**Comment by Nyborg1** [comment]
Tabel og tekst er for stor til at vise indhold - Der skal helst vises flere linjer for at det giver mening med en tabel, som hænger sammen med kortet

![2023-09-25 12_26_27-Kort og GIS - Nyborg Intranet – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/551be96e-838f-47d5-91aa-36a8d7b8805e)

**Comment by mapcentia** [comment]
Se #69

**Comment by Nyborg1** [comment]
Tabelvisning vises fint internt når grundejerforeninger fra _vidi.nyborg.dk_ bruges embeded
Tabelvisning vises også rigtigt eksternt med data fra fra _kort.nyborg.dk_ 
Jeg har skrevet til Nyborgs webredaktør og bedt hende skifte token og tilhørende -div- 
Test er først muligt når det sker

**Comment by Nyborg1** [comment]
Tabellen _01_fysisk_plan_og_naturbeskyt.**grundejerforeninger** kan redigeres internt.
Men den skal ikke kunne redigeres eksternt.
Hvordan fjerner man Edit-blyanten fra infovinduet på den eksterne side?

[](https://www.nyborg.dk/da/borger-og-selvbetjening/bolig-og-byggeri/dit-hus-og-grund/grundejerforeninger/)

data-vidi-signin="none" er sat på sammen med token -  Måske virker dette ikke i den nye eksterne - Embed.js

**Comment by Nyborg1** [comment]
![2023-11-06 14_13_51-Grundejerforeninger - Nyborg dk – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/193f736a-331c-4b6c-9ac3-e742fee193d0)

**Comment by mapcentia** [comment]
Prøv at fjerne "edit" fra "enabledExtensions". Det skulle helt fjerne alle editor funktioner fra alle lag.

Virker data-vidi-signin="none" ikke? Kan du stadig se login kanppen?

**Comment by Nyborg1** [comment]
:-) Men jeg vil jo gerne kunne editere i den interne opsætning.
loginknappen kan ikke ses i den eksterne efter data-vidi-signin="none" er sat på.
Men blyanten kommer på når Info bruges. Der kommer fejl hvis man forsøger at submitte rettelser

![image](https://github.com/Nyborg1/nyborg_gis/assets/95336810/3dce3274-0b0d-4e81-b62c-243a94d5b12e)

**Comment by mapcentia** [comment]
Vi skal vist have lavet noget lign.: data-vidi-editor="none", som fjerner blyant mv. Jeg kigger på det

**Comment by Nyborg1** [comment]
Er der noget nyt til løsning af dette ?

**Comment by Nyborg1** [comment]
Vi har opdaget at det er  muligt at redigere i data uden være logget!

**Comment by mapcentia** [comment]
Men ændringerne bliver ikke gemt. Hvis man så logger pp efterfølgende, vil ændringer blive gemt.

I GeoFA sammenhæng har vi besluttet at lave det sådan, at man kan konfigurere, at man skal være logget ind, før man ser værktøjerne til editering. Den har høj prioritet, så den kommer snart

**Comment by Nyborg1** [comment]
Man kan rette i data uden at være logget ind når VIDI vises som embeded.
Prøv selv på 
https://www.nyborg.dk/da/borger-og-selvbetjening/bolig-og-byggeri/dit-hus-og-grund/grundejerforeninger/

Det er fint hvis vi fremover kan konfigurere kan se redigeringmulighederne.

**Comment by mapcentia** [comment]
Du skal fjerne "editor" fra enabledExtensions. Jeg har lige gjort det på ydersiden, men det skal gøres på indersiden inden synkroniseringen kører. Man kan så have to configs: En til editering og en til hjemmesiden

**Comment by Nyborg1** [comment]
ok - 
Det er jo også sådan vi gør i grundsaglsopsætningen

**Comment by Nyborg1** [comment]
Der er nu 2 forskellige konfigurationer. 

Én configuration_grundejerforeninger som bruges til at vise grundejerforeninger eksternt
https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_grundejerforeninger_6451001534aa4734922832.json#Seneste_luftfoto_matr_adr_vej/12/10.6648/55.2545/v:_01_fysisk_plan_og_naturbeskyt.grundejerforeninger
Vises også embeded på nyborg.dk
https://www.nyborg.dk/da/borger-og-selvbetjening/bolig-og-byggeri/dit-hus-og-grund/grundejerforeninger/

Og én configuration_grundejerforeninger_edit som kan bruges til at redigere internt.
https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_grundejerforeninger_edit_65e03fe13e399025317041.json#Seneste_luftfoto_matr_adr_vej/12/10.7766/55.3248/v:_01_fysisk_plan_og_naturbeskyt.grundejerforeninger

**Comment by Nyborg1** [comment]
https://github.com/Nyborg1/nyborg_gis/issues/85
