### ISSUE TITLE
Ny VIDI Konfiguration

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#71]
Er det muligt at få VIDI til at starte op med lagmenuen åben?

![2023-10-03 08_37_46-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/a922c4df-1e3e-4e17-b21e-cddd42b7333d)

**Comment by mapcentia** [comment]
Og få at åbne første gruppe i lagtræet:

`"showLayerGroupCheckbox": true`
