### ISSUE TITLE
Fejl i user mapping til foreign datawrapper til GeoFyns database

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#72]
Alle foreign tables fra geofyn fejler pga. forkert user mapping.

En personlige bruger **ptjo** er åbentbart blevet brugt i nbpostgis.
Det er oprydning i dette der har gjort at det fejler.

Kan du hjælpe med at fixe dette?

**Comment by Nyborg1** [comment]
Fx dette dataset
"geus_geofyn_nb"."jupiter_bor_vandfors_almen_ws" relation.
The error message from the database was:
ERROR: user mapping not found for "ptjo"
SQL: SELECT * FROM "geus_geofyn_nb"."jupiter_bor_vandfors_almen_ws" LIMIT 1

**Comment by mapcentia** [comment]
Der er ikke en fejl.

"jupiter_bor_vandfors_almen_ws" er en fremmed tabel, som anvender serveren "geofyn_nb". Til denne server er der to user mappings: gis_read og postgres

Hvis du ser: ERROR: user mapping not found for "ptjo", når du select'er fra "jupiter_bor_vandfors_almen_ws", er det fordi du forbinder med user ptjo som ikke har en user mapping.

Hvis jeg kører select på tabellen med user postgres er der ingen problem.

Så enten skal du forbinde med en anden user eller der skal oprettes en user mapping til ptjo

**Comment by Nyborg1** [comment]
Okay
Men hvad er der gået galt.
Brugeren "ptjo" skal ikke bruges i GC2 og VIDI

**Comment by mapcentia** [comment]
Hvor ser du fejlen: ERROR: user mapping not found for "ptjo"
?

**Comment by Nyborg1** [comment]
Fejlen er fra QGIS.🙃
På flere lag fra Geofyn. Fx dtm højdekurver. Måske er det flere sammenfaldne fejl

**Comment by mapcentia** [comment]
Hvilken user anvender du i QGIS?

**Comment by Nyborg1** [comment]
Det burde være en postgres user ~ jeg ka tjekke det lidt senere. QGIS har det med at gemme min ad-bruger. Det ka være at ptjo fejlagtigt kommer med fra QGIS-projektfilerne læses ind i GC2

**Comment by Nyborg1** [comment]
Jeg kan ikke rigtigt gennemskue hvad er der kommer med (ud over tematisering) når jeg indlæser qgs-projekter i GC2.
Kan man ikke bruge qlr-filer til at styre indlæsningen i stedet for.

**Comment by mapcentia** [comment]
Vi skal lige holde tungen lige i munden. Dette issue har vel ikke noget med GC2 at gøre? Jeg har opfattet det sådant, at fejlen kommer, når du forbinder fra QGIS til Postgis serveren?

**Comment by Nyborg1** [comment]
ja det har du ret i. Men jeg vil gerne have din assistance. Det er ikke sikkert at det påvirker adgangen til data i GC2. Men bruger skal have adgang til data både via QGIS og GC2.
Kan du se hvor "ptjo" har owner rettigheder i nbpostgis

**Comment by Nyborg1** [comment]
Jeg har fundet 2 lag der fejler i GC2. Der er :
dhm_geofyn_nb.kurver_05m_2018_450.the_geom
og 
geus_geofyn_nb.jupiter_bor_vandfors_almen_ws
Men det har ikke noget med forkert user-mapping at gøre

**Comment by Nyborg1** [comment]
Ved ikke om disse noter hjælper!
I QGIS plejer jeg at logge ind på nbpostgis med superuser "GIS" 

"ptjo" er min ad-bruger som jeg ikke rigtigt ved hvad skal i databasen
Men ptjo står i qgs-filerne

**Comment by mapcentia** [comment]
Når ptjo anvendes skal der være en user-mapping for brugeren. Så den har jeg sat ind. Du kan så skifte brugeren i QGIS og vi kan efterfølgende fjerne user-mapping for ptjo.

De to fremmed-tabeller *dhm_geofyn_nb.kurver_05m_2018_450* og *geus_geofyn_nb.jupiter_bor_vandfors_almen_ws* havde ikke et fel kaldet "gid". Views og fremmed-tabeller skal have dette felt, som GC2 vælger som primær nøgle (views og fremmed tabeller har jo ikke en rigtig primær nøgle). Jeg omdøbte blot feltet ogc_fid til gid i GC2 Admin.

**Comment by Nyborg1** [comment]
Tak Martin.
Det virker :-)
Jeg prøver at luge ud i ptjo´s login via QGIS.
Men jeg er nok nødt til at have din hjælp til at slette brugeren helt i databasen.

Ift. til foreign tables er spørgsmålet hvad der sker når disse opdateres næste gang i Nyborgs database.
Hvor kommer data fra?
Der er ikke en gid kolonne i modertabellen hos dhm.kurver_05m_2018_450 og jeg kan ikke finde noget der hedder i dhm_nyborg
