### ISSUE TITLE
Skolevej beregner ingen ruter

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#74]
Skoleruterne bliver ikke længere vist på vores test-site hos Geo Fyn.
https://geofyn-test.gc2.io/app/geofyn/?config=/api/v2/configuration/geofyn/configuration_skolevej_6441adf653bc9997692381.json&dps=1

**Comment by mapcentia** [comment]
Kigger på det

**Comment by Nyborg1** [comment]
Hvis du og Jesper er ved at  opgraderer GeoFyns VIDI - Så vil jeg gerne have skolevej ændret. 
Url'en hedder stadig geofyn-**test**.gc2.io

**Comment by mapcentia** [comment]
Så virker det igen. Den anden dag blev Postgres opgraderet fra 14.7 til 14.8 og det betød at extension pgrouting "gik i stykker". Det kunne dog heldigvis flxes ved at fjerne extensionen og installere den igen.

Ny Vidi er stdaig til test i Geo Fyn. Når Jesper tager springet, vil der kun være én Vidi, så geofyn-test.gc2.io vil blive ændret der.

**Comment by Nyborg1** [comment]
Det virker igen og jeg har meldt det videre til sagsbehandlerne
