### ISSUE TITLE
Modul - Brevflet - kald til LIFA EjdExplorer i ny VIDI

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#75]
Opgradering af Modul:

Eksisterende funktionalitet:
Find adresser 
Kald af af desktop-programmet med de udvalgte adresser.

Ny funktionalitet:
Udvælg matrikler 
Kald af og åbning af Ejdexplorer med de udvalgte matrikler
I følge LIFA skal EjdExplorer startes med denne for at slå en eller flere matrikler op.

ejdexpl://?mode=single&CadastralDistrictIdentifier=411355,411355,331751&RealPropertyKey=9b,12d,6u

![image](https://github.com/Nyborg1/nyborg_gis/assets/95336810/b93a0965-2314-40e3-8e81-ff6e7fc467d7)

**Comment by mapcentia** [comment]
@Nyborg1 Brevflet (og Ejendom) modulerne er nu opgraderet til Ny Vidi. Jeg har installeret en test version internt, som anvender den interne GC2. Dvs. at configs kan testes i Ny Vidi.

Man skifter blot `https://vidi.nyborg.dk` ud med `http://172.16.1.99:3000`:

`https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_test_62eacc1f6a941575171079.json`

`http://172.16.1.99:3000/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_test_62eacc1f6a941575171079.json`

**Comment by Nyborg1** [comment]
Fantastisk Martin.
Så vil jeg teste lidt.
I forhold til opgradering / udvikling af funktionalitet har jeg har oprettet et tilsvarende issue i VIDI / GC2 brugergruppen. 
https://github.com/gc2vidi/Udvikling-og-vedligeholdelse/issues/11

Hvis Kristoffer og Emil skal byde ind på funktionaliteten - Så kan vi måske skrive den del af issuet der.

**Comment by mapcentia** [comment]
Spørgsmål sendt til LIFA:

I dag bruger jeg LIFAExternalIntegrationServiceREST således, hvor adresserne er "samlet op" på et kort:

POST https://www.kortviser.dk/UsersPublic/Handlers/LIFAExternalIntegrationServiceREST.ashx
municipalitycode=0450,0450&streetcode=1128,1128&housecode=33B,33A

Og så kaldes EjdExplorer med det returnerede LIFAExternalIntegrationServiceID:

ejdexpl://?mode=merge&LIFAExternalIntegrationServiceID=3556549

Kan man poste ejerlavskoder og matrikelnumre til LIFAExternalIntegrationServiceREST,  i stedet for adresser? Eller skal matrikeloplysninger sendes direkte til EjdExplorer ala det her:

ejdexpl://?mode=single&CadastralDistrictIdentifier=411355,411355,331751&RealPropertyKey=9b,12d,6u

**Comment by Nyborg1** [comment]
Jeg har lige testet matrikelopslag i VIDI test:
http://172.16.1.99:3000/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_test_62eacc1f6a941575171079.json

Der kommer en fin liste i VIDI - Men EjdExplorer v 2.9.1 åbnes _ikke_ med de valgte matrikler!
Ved ikke om LIFA læser issues her - men har sendt dem en mail

**Comment by Nyborg1** [comment]
Martin vil du prøve at ændre den streng der sendes fra VIDI til EjdExplorer.

Ligenu står der "single"
Hvis den rettes til "merge" - så åbner EjdExplorer korrekt med en matrikelliste

ejdexpl://?mode=**merge**&CadastralDistrictIdentifier=411752,411755&RealPropertyKey=3a,2a

**Comment by mapcentia** [comment]
Så er single rettet til merge

**Comment by Nyborg1** [comment]
Tak, Martin.
Nu åbner EjdExplorer i den rigtige fane - med en matrikelliste.
Jeg mangler fortsat en bekræftelse fra LIFA på at det er den rigtige metode!!
Opgradering af den interne VIDI afventer installation af den nye EjdExplorer til alle ansatte i Teknik & Miljø

**Comment by Nyborg1** [comment]
Der er en lille detalje i brugerfladen som du gerne må rette ved lejlighed.
Der skal stå "Valgte matrikler " når det er matrikler der vælges. Og "Valgte adresser" når det er adressepunkter der vælges.
Alternativt kan der stå "Valgte elementer"

![valgte_matrikler](https://github.com/Nyborg1/nyborg_gis/assets/95336810/11d8f46b-746c-407b-a76b-f06c271cfa79)

**Comment by mapcentia** [comment]
Den er ikke fosvundet, men skal aktiveres i config'en:
![image](https://github.com/Nyborg1/nyborg_gis/assets/3850918/c0b69c4c-a2d3-4d97-9205-9e1b75cda1ab)

**Comment by Nyborg1** [comment]
#85

**Comment by Nyborg1** [comment]
Kaldet til ejdexplorer virker ikke længere for adresser.
Det lader til at den streng der bliver sendt fra VIDI ikke længere giver et svar

ejdexpl://?mode=merge&LIFAExternalIntegrationServiceID=3646884

Matrikelkald til EjdExplorer virker fint
ejdexpl://?mode=merge&CadastralDistrictIdentifier=411151,411151,411151,411151,411151,411151,411151,411151&RealPropertyKey=1ci,1ck,1cl,1hx,1hv,1hu,1hy,1ht

Er det LIFA´s LIFAExternalIntegrationServiceREST der er problemet?

**Comment by Nyborg1** [comment]
LIFA har løst problemet.
De havde ændret servicen så den skulle have https
Det virker igen efter at de har stillet det tilbage til almindlig http
