### ISSUE TITLE
Chrome out of memory

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#76]
Der er noget galt med den interne VIDI i Chrome.
VIDI går helt i stå ved load af data. 
fx Gruppen "planlægning".
Denne gruppe temaer lag fungerer fint på den eksterne VIDI

**Comment by mapcentia** [comment]
Kan du ikke lige lægge URLen til Vidi ud?

Umiddelbart loader lag fint fx her:
https://vidi.nyborg.dk/app/nyborg_gis/?
config=/api/v2/configuration/nyborg_gis/configuration_drift_63c91a8be08d1318765497.json#Basis_kort/17/10.7905/55.3132/_05_07_snedrydning.vinterdata_2023_f

**Comment by Nyborg1** [comment]
Intern config
https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_intern_623d925bf2a5a285566709.json#Basis_kort/17/10.782/55.3094/

**Comment by Nyborg1** [comment]
Ekstern config

https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_kortnyborg_62f4e0f32ccda467979749.json#Basis_kort/11/10.747/55.2991/_00_grundkort.passepartout

**Comment by Nyborg1** [comment]
Det kan være at det har noget med data at gøre. Disse konfigurationer har begge gruppen "Planlægning"

**Comment by Nyborg1** [comment]
Det er åbenbart kun i min chrome der er problemer. Det virker fint Edge. Så jeg har en workaround

**Comment by Nyborg1** [comment]
Problemet er væk - og kan ikke genskabes

**Comment by Nyborg1** [comment]
Er der noget der kan gøres ved hukommelsesforbruget når kortsiderne loades?

![fejl_Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/fe954a6a-b742-43b0-9e01-c4c000f9ba7d)

Måske er der nogle fejl uhensigtsmæssigheder i de VIDI-konfigurationer der bruges - fx på denne intranetsideside, hvor jeg har samlet nogle eksempler

https://intranet.nyborg.dk/da/vores-arbejdsplads/din-afdeling/teknik-miljo-og-erhverv/klima-plan-og-natur/kort-og-gis-i-teknik-og-miljo-plan-og-natur/webgis

**Comment by Nyborg1** [comment]
Det prøver jeg at bestille.
Men det er ikke sikkert at du med din vpn-bruger får adgang til Intranettet.
Problemet med Chrome hukommelsen kan du måske opklare via min skærm på et team-møde

**Comment by Nyborg1** [comment]
Den eksterne VIDI som bruges til grundsalgsannoncering har de samme fejl / advarsler
https://www.nyborg.dk/da/borger-og-selvbetjening/bolig-og-byggeri/vil-du-bygge/villagrunde-bolig-og-byggeri/

**Comment by Nyborg1** [comment]
![2024-04-09 15_22_53-Villagrunde, bolig og byggeri - Nyborg dk – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/be054025-be46-4fa1-b7f2-86197a9655a7)

**Comment by Nyborg1** [comment]
Andet  lidt simplere eksempel på intern config som dør - out of memory.
https://vidi.nyborg.dk/app/nyborg_gis/?state=state_snapshot_2abaf590-f199-11ee-ab64-535eb567e2a7&config=/api/v2/configuration/nyborg_gis/configuration_kortnyborg_62f4e0f32ccda467979749.json&dps=1

**Comment by Nyborg1** [comment]
![2024-04-10 15_37_20-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/57ac59be-76be-4343-8823-0f80711d8b1a)

**Comment by Nyborg1** [comment]
Med dette state-snapshot kan man fremtvinge fejl hver gang.
https://vidi.nyborg.dk/app/nyborg_gis/?state=state_snapshot_2abaf590-f199-11ee-ab64-535eb567e2a7&config=/api/v2/configuration/nyborg_gis/configuration_kortnyborg_62f4e0f32ccda467979749.json&dps=1

**Comment by mapcentia** [comment]
Jeg fik samme out-of-memory når jeg brugte Chrome på Windows serveren. Den installerede Chrome er 32-bit versionen, som ikke kan tilgå særlig meget hukommelse og det er som om, at 32-bit versionen også bruger en del mere hukommelse. Windows på serveren er 64-bit, så løsningen der, var at installere Chrome 64-bit. Der kan være forskellige grunde til, at I bruger 32-bit versionen?

**Comment by Nyborg1** [comment]
IT kommer ikke til at opdatere Chrome til en 64 bit foreløbig.
Workaround.  VIDI skal fremover åbnes i Edge - som er preinstalleret på Nyborgs pc'ere i en 64 bit version.
Genvej til VIDI og Edge skal ud til brugerne
