### ISSUE TITLE
Zoom / centrering uhensigtsmæssig

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#78]
Problemet opstår når brugeren er zoomet ind på en enkelt matrikel.
Der klikkes Info på fx en lokalplan. 
Herefter klikkes på linket til dok. med lokalplantekst
Så ændres kortet og centreringen til den geometri der spørges på.
Og brugeren bliver irriteret over igen at skulle finde det aktuelle sted

Det ser ud som om det er et problem  i både den ’gamle’ VIDI-brugerflade og i den nye VIDI version.

Løsning kunne være at Infoboks bliver i det aktuelle kortvindue

![2024-02-05 15_34_00-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/a1bc3adf-bba3-4153-846b-c193ab550845)

![2024-02-05 15_34_13-MapCentia Vidi – Google Chrome](https://github.com/Nyborg1/nyborg_gis/assets/95336810/f50ff4a7-530e-4e2b-988d-7adb435340a0)

**Comment by Nyborg1** [comment]
løst ved at insætte denne i config
 "crossMultiSelect": true,

**Comment by Nyborg1** [comment]
Crossmultiselect giver udfordringer i visningen af Tinglysningsdata fra Geopartner

Med Crossmultiselect
![image](https://github.com/Nyborg1/nyborg_gis/assets/95336810/d976d476-09ab-4d20-987f-7deaf0598939)

Uden Crossmultiselect
![image](https://github.com/Nyborg1/nyborg_gis/assets/95336810/f30dbe5f-97d7-4565-af02-02a4842b141e)

**Comment by Larsklindt** [comment]
Hej Peter. Vi har haft lidt det samme problem i Geopartner, at kilk på et element i tabellen edmfører at kortet automatisk zoomer og panorerer. vi har i stedet for anvendt denne indstilling: [https://vidi.readthedocs.io/da/latest/pages/standard/91_run_configuration.html#featureinfotableonmap](url)

**Comment by Nyborg1** [comment]
Det er noteret. Tak
Kan featureinfotableonmap også sættespå tabel-niveau i Meta?

**Comment by Larsklindt** [comment]
Nej, desværre - det er en generel parameter i config, der gælder for alle lags infovisning.



Med venlig hilsen

Lars Klindt
GIS-konsulent

Mobil +45 2858 1660
***@***.***

***@***.***<https://dk.linkedin.com/company/geopartner-landinspekt-rer>
Geopartner Landinspektører A/S' ydelser leveres i henhold til vores forretningsbetingelser<https://geopartner.dk/forretningsbetingelser/>
og i overensstemmelse med vores persondatapolitik<persondatapolitik.geopartner.dk> - CVR 20014784
Fra: Peter Jørgensen ***@***.***>
Sendt: 17. april 2024 15:20
Til: Nyborg1/nyborg_gis ***@***.***>
Cc: Lars Klindt ***@***.***>; Assign ***@***.***>
Emne: Re: [Nyborg1/nyborg_gis] Zoom / centrering uhensigtsmæssig (Issue #78)


Det er noteret. Tak
Kan featureinfotableonmap også sættespå tabel-niveau i Meta?

**Comment by Nyborg1** [comment]
?  Jeg kan ikke lige gennemskue om jeg i en konfiguration med mange lag kan styre info-visningen ved at sætte crossmulitiselect på nogle lag og have featureinfotableonmap=false

**Comment by Larsklindt** [comment]
Hej Peter.

Jeg tror ikke disse to kan kombineres. Jeg vil umiddelbart mene at featureinfotableonmap, overstyrer andre indstillinger.



Med venlig hilsen

Lars Klindt
GIS-konsulent

Mobil +45 2858 1660
***@***.***

***@***.***<https://dk.linkedin.com/company/geopartner-landinspekt-rer>
Geopartner Landinspektører A/S' ydelser leveres i henhold til vores forretningsbetingelser<https://geopartner.dk/forretningsbetingelser/>
og i overensstemmelse med vores persondatapolitik<persondatapolitik.geopartner.dk> - CVR 20014784
Fra: Peter Jørgensen ***@***.***>
Sendt: 17. april 2024 16:10
Til: Nyborg1/nyborg_gis ***@***.***>
Cc: Lars Klindt ***@***.***>; Assign ***@***.***>
Emne: Re: [Nyborg1/nyborg_gis] Zoom / centrering uhensigtsmæssig (Issue #78)


? Jeg kan ikke lige gennemskue om jeg i en konfiguration med mange lag kan styre info-visningen ved at sætte crossmulitiselect på nogle lag og have featureinfotableonmap=false

**Comment by Nyborg1** [comment]
Hej Martin 
Kan man styre zoom på en anden måde?
Alternativt vil jeg gerne have en workaround hvor jeg på udvalgte tabeller kan udnytte crossmultiselect. 
Hvor i Meta kan jeg skrive "crossMultiSelect": true,
plandatadk_geofyn_nb.pdk_kommuneplantillaeg_vedtaget_v

**Comment by Nyborg1** [comment]
Klik-info - popup fejler i konfiguration test
#83

**Comment by mapcentia** [comment]
Det er faktisk ikke standard, at der auto panes til pop-up'en. Men det var slået til i config'en:

` "autoPanPopup": true,`

Jeg har ændret til `false` (den kan også fjernes helt)
