### ISSUE TITLE
Positivliste med skemaer der skal vises eksternt

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#8]
Ved ikke lige hvilket format (json?) Og hvor den skal placeres - i skema=settings

**Comment by Nyborg1** [comment]
{
	   "schemata": [
"_00_grundkort"
,"_01_fysisk_plan_og_naturbeskyt"
//,"_02_byggeri"
,"_03_boliger"
//,"_04_parker_fritids_idraetsanlaeg_landskabspleje"
//,"_05_veje_trafik"
//,"_06_spildevand_vandlob"
,"_07_affald_genanvendelse"
,"_09_miljoebeskyttelse"
//,"_13_forsyning"
,"_14_beredskab"
,"_17_undervisning"
,"_19_kulturhistoriske_institutioner"
,"_20_kulturvirksomhed"
,"_21_biblioteker"
,"_24_erhvervsforhold"
,"_27_socialservice"
,"_28_dagtilbud"
,"_29_sundhed"
,"_54_uddannelse"
//,"_82_02_salg_kommunal_ejendom"
,"_84_offenntlige_valg"
//,"_82_16_udlaan_udleje_lok_ejend"
,"dagi_geofyn_nb"
,"danmarksarealinformation_geofyn_nb"
,"distrikter_geofyn_nb"
,"dkjord_geofyn_nb"
,"fynbus_geofyn_nb"
,"geodanmark_geofyn_nb"
,"geus_geofyn_nb"
,"grukos_geofyn_nb"
,"havvandsstigninger_geofyn_nb"
,"husdyr_geofyn_nb"
,"indbyggertal_geofyn_nb"
,"jordbrugsanalyser_geofyn_nb"
,"kb_geofyn_nb"
//,"kommuneplan21_eplan
,"kulturarvsstyrelsen_geofyn_nb"
,"kystatlas_geofyn_nb"
,"landbrugsdrift_geofyn_nb"
,"lertykkelse_geofyn_nb"
,"mastedatabasen_geofyn_nb"
,"matrikel_geofyn_nb"
,"naturdatabasen_geofyn_nb"
,"naturerhvervsstyrelsen_geofyn_nb"
,"noegletaldk_geofyn_nb"
,"overfladevand_og_luft_geofyn_nb"
,"plandatadk_geofyn_nb"
,"politidata_geofyn_nb"
,"public"
,"puls_geofyn_nb"
,"redningsnumre_geofyn_nb"
,"vd_naboretsdata_geofyn_nb"
,"uddannelse_geofyn_nb"
,"udinaturen_geofyn_nb"
,"vandplaner_geofyn_nb"
,"vejdirektoratet_geofyn_nb"
]
}

**Comment by mapcentia** [comment]
Sync er sat op med følgende liste:

_00_grundkort
_01_fysisk_plan_og_naturbeskyt
_03_boliger
_07_affald_genanvendelse
_09_miljoebeskyttelse
_14_beredskab
_17_undervisning
_19_kulturhistoriske_institutioner
_20_kulturvirksomhed
_21_biblioteker
_24_erhvervsforhold
_27_socialservice
_28_dagtilbud
_29_sundhed
_54_uddannelse
_84_offenntlige_valg
dagi_geofyn_nb
danmarksarealinformation_geofyn_nb
distrikter_geofyn_nb
dkjord_geofyn_nb
fynbus_geofyn_nb
geodanmark_geofyn_nb
geus_geofyn_nb
grukos_geofyn_nb
havvandsstigninger_geofyn_nb
husdyr_geofyn_nb
indbyggertal_geofyn_nb
jordbrugsanalyser_geofyn_nb
kb_geofyn_nb
kulturarvsstyrelsen_geofyn_nb
kystatlas_geofyn_nb
landbrugsdrift_geofyn_nb
lertykkelse_geofyn_nb
mastedatabasen_geofyn_nb
matrikel_geofyn_nb
naturdatabasen_geofyn_nb
naturerhvervsstyrelsen_geofyn_nb
noegletaldk_geofyn_nb
overfladevand_og_luft_geofyn_nb
plandatadk_geofyn_nb
politidata_geofyn_nb
public
puls_geofyn_nb
redningsnumre_geofyn_nb
vd_naboretsdata_geofyn_nb
uddannelse_geofyn_nb
udinaturen_geofyn_nb
vandplaner_geofyn_nb
vejdirektoratet_geofyn_nb

**Comment by Nyborg1** [comment]
Er det muligt at styre mere detaljeret hvad der bliver synkroniseret til den eksterne server - 
Som jeg har forstået det er det pt kun data i skemaerne der kan whitelistes  

Til det interne setup har jeg tagget og konfigureret "byggesag":

Men jeg kan se alle konfigurationer på det offentlige site. (Bortset fra de skemaer der er udeladt.)

https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_byggesag_62d91f5de8e25661721514.json#orto_sommer_2022/12/10.7767/55.3023/

**Comment by Nyborg1** [comment]
Fx vises også extentions som konfliktsøgning og EjdExplorer eksternt

**Comment by Nyborg1** [comment]
I Spatial Suite har man en post-command-job som erstatter eller fjerner det der ikke skal synkroniseres

**Comment by Nyborg1** [comment]
Wiki side.
https://github.com/Nyborg1/nyborg_gis/wiki/Kort.nyborg.dk

**Comment by Nyborg1** [comment]
Whitelist er placeret her: /opt/gc2/nyborg/sync/whitelist.txt Redigeres med Filezilla
