### ISSUE TITLE
Fejl på pdk_lokalplan_vedtaget_v fra Geo Fyn

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#81]
Foreign table plandatadk_geofyn_nb.pdk_lokalplan_vedtaget_v har ikke en korrekt ID

SQLSTATE[42703]: Undefined column: 7 ERROR: column "fid" does not exist LINE 1: ..._m22","minuds8","maxbhjd2","maxetage2","maxbhjd6","fid","sfo... ^ HINT: Perhaps you meant to reference the column "pdk_lokalplan_vedtaget_v.gid" or the column "pdk_lokalplan_vedtaget_v.id".

**Comment by Nyborg1** [comment]
Der er samme fejl på
plandatadk_geofyn_nb.pdk_lokalplan_forslag_v
kulturarvsstyrelsen_geofyn_nb.bygning_fredningstatus_hoej

**Comment by Nyborg1** [comment]
Nu er der kun fejl på denne.
kulturarvsstyrelsen_geofyn_nb.bygning_fredningstatus_hoej

**Comment by mapcentia** [comment]
Virker nu. Det var fremmed tabellerne hos geofyn > nyborg som ikke var opdaterede
