### ISSUE TITLE
Klik-info - popup fejler i konfiguration test

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#83]
Hvordan og hvornår vises klikinfo-popup . 
Der er forskel på visning i forskellige lag. Nogle gange vises atrributter i højre-panel andre gange som popup.

Det er ikke de valgte lag der vises

![image](https://github.com/Nyborg1/nyborg_gis/assets/95336810/912e1fa4-86ed-4dda-b0e3-5e7d503e7a3d)

Eks.
dk_geofyn_nb.pdk_lokalplan_vedtaget_v  og _01_fysisk_plan_og_naturbeskyt.grundejerforeninger.
I begge lag er der flueben ved klikinfo på tabellen.

Crossmultiselect er fjernet fra den interne konfiguration!
**Test i intern VIDI - gl. version**
https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_test_62eacc1f6a941575171079.json#Basis_kort/15/10.7618/55.3106/v:_01_fysisk_plan_og_naturbeskyt.grundejerforeninger,plandatadk_geofyn_nb.pdk_kommuneplanramme_vedtaget_v,plandatadk_geofyn_nb.pdk_lokalplan_vedtaget_v

Med crossmultiselct
**Test i ny VIDI**
http://172.16.1.99:3000/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_test_62eacc1f6a941575171079.json#Basis_kort/15/10.7618/55.3106/v:_01_fysisk_plan_og_naturbeskyt.grundejerforeninger,plandatadk_geofyn_nb.pdk_kommuneplanramme_vedtaget_v,plandatadk_geofyn_nb.pdk_lokalplan_vedtaget_v

**Comment by mapcentia** [comment]
Med default indstillinger (uden crossMultiSelect) vises feature-info i panelet under Info. Hvis der kun rammes én feature på tværs af alle lag, åbnes pop-up'en for denne feature. Ved flere hits, åbnes pop-up'en først når en feature vælges i tabellen under Info. Det er det forventlige i både ny og gamle Vidi.
