### ISSUE TITLE
Skift til ny VIDI internt

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#85]
**Der er følgende udfordringer der skal løses inden.**

http://172.16.1.99:3000/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_test_62eacc1f6a941575171079.json#Basis_kort/12/10.7767/55.3023/

Konfliksøg medtager ikke alle 91 temalag som den nuværende **configuration_intern**!
https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_test_62eacc1f6a941575171079.json#Basis_kort/12/10.7767/55.3023/

Kan du fixe det og kan vi aftale en dato for skiftet?

**Comment by Nyborg1** [comment]
Konfliktsøgnings rapport zoomer ikke til det området der er valgt
![2024-05-13 10_28_35-MapCentia Vidi og 1 side mere - Arbejde - Microsoft​ Edge](https://github.com/Nyborg1/nyborg_gis/assets/95336810/8320b1bf-0d52-4b0a-b997-5ff8e326bb3b)

**Comment by mapcentia** [comment]
Både den nye og gamle Vidi søger gennem 69 temaer?

**Comment by Nyborg1** [comment]
:-) Du har ret. Der er ikke noget problem. Det er en anden konfiguration der bruges i test - andre tags). konfugurationen "byggesag" har 91 temaer i konfliktsøgningen. 

Hvilken dato skal vi aftale i forhold til bruge den nye VIDI alle steder internt

**Comment by Nyborg1** [comment]
Er du gået i gang? Ring når det er klar! Jeg vil gerne teste at det virker i konfiguration byggesag [https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_byggesag_62d91f5de8e25661721514.json#orto_foraar/12/10.6979/55.2959/_01_04_matrikulaere_forhold.ejerlav,vd_naboretsdata_geofyn_nb.vejprojekter_vejinteressezoner,vd_naboretsdata_geofyn_nb.nr_byggelinjer,danmarksarealinformation_geofyn_nb.habitat_omr,_05_01_01_vejnavne_husnr.vejnavne_basiskort_1_50000,_05_01_01_vejnavne_husnr.husnummer_basiskort_1_4000,_00_grundkort.passepartout,_01_04_matrikulaere_forhold.matrikel_1_4000_wms,dkjord_geofyn_nb.dkjord_v2,dkjord_geofyn_nb.dkjord_v1,plandatadk_geofyn_nb.pdk_lokalplan_vedtaget_v,plandatadk_geofyn_nb.pdk_lokalplandelomraade_vedtaget_v](url)

og i den samlede interne konfiguration
[https://vidi.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_intern_623d925bf2a5a285566709.json#Basis_kort/11/10.6735/55.285/](url)
