### ISSUE TITLE
Fejli Safari-browser

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#88]
Der er  nogle funktioner som fejler i Safari.
Jeg ved ikke om det er 

"autoPanPopup" eller "crossmultiselect"

Dette site virker ikke
https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_drift_63c91a8be08d1318765497.json#Basis_kort/12/10.7767/55.3023/

Dette virker
https://kort.nyborg.dk/app/nyborg_gis/?config=/api/v2/configuration/nyborg_gis/configuration_kortnyborg_62f4e0f32ccda467979749.json#Basis_kort/11/10.747/55.2991/_00_grundkort.passepartout

**Comment by Nyborg1** [comment]
![config](https://github.com/user-attachments/assets/5355c141-f162-4dc8-848c-312665492150)

**Comment by Nyborg1** [comment]
På Ipad / Iphone åbner VIDI med leftpanel åbent. Når man forsøger at lukke dette kommer denne fejl.
![Image](https://github.com/user-attachments/assets/4cb84626-c613-4b66-8400-764469b2b085)

**Comment by Nyborg1** [comment]
Efter lidt fejlsøgning gætter jeg på at det har noget med denne funktion at gøre    
**"showOffcanvas": false,**
Hvis den står til false - kommer fejlen først efter at venstremenuen er slås til og fra på enheden.

**Comment by Nyborg1** [comment]
Det lykkedes mig at få adgang via en gammel Ipad.
Der er fortsat et problem hvis venstrepanelet åbnes og lukkes på en nyere version - fx en Iphone 16

iOS 16.7.10 (Ipad)  Ok
**iOS 18.0.1   (Iphone)  No go**

**Comment by mapcentia** [comment]
Ok, jeg har genskabt fejlen på iPhone 16 pro med IOS 18

**Comment by mapcentia** [comment]
Når man slår menuen ind, så refresher browseren. Og sommetider melder den så, at den ikke kan indlæse siden. Det er ikke til at sige hvad, som får den til det. Det virker nærmest som om, det er en bug i Safari. Men heldigvis ser fejlen ud til at forsvinde, hvis allernyeste Vidi anvendes - den med mulighed for Dark mode, så den har jeg rullet ud.

Det er bekymrende, at sådanne fejl dukker op på så udbredt en platform som IOS
