### ISSUE TITLE
Data - tabel vises ikke i VIDI

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#9]
_05_veje_trafik.skilte-kampagner bliver ikke vist.
Tabellen er simpel og har kun geometrien point.

Tabel er korrekt indlæst i nyborg_gis og kan tilgås via QGIS
tabel er tildelt gruppe
tabel har tags
tabel kan ses i gc2-database-vindue

**Comment by mapcentia** [comment]
QGIS styling slår ikke igennem fordi data-source i QGS filen ikke er PostGIS men filen `skilte-kampagner.gpkg`

**Comment by Nyborg1** [comment]
okay - Jeg er nødt til nogen gange at bruge gpkg-formatet som mellemstation fra en MapInfo.tab - inden den overføres til databasen.  Jeg overfører den til databasen igen. Det er nok en af de tabeller der er lagt i version 13 - databasen.

**Comment by mapcentia** [comment]
Kan den ikke lukkes?
